-- Context: config_story
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('lblStoryTitle', '**Story Title:**', 'en', 1),
('lblQuickMode', 'Quick Mode?:', 'en', 1),
('lblTurnLength', 'Turn Length (hours):', 'en', 1),
('lblTimeoutReminder', 'Reminder Timing:', 'en', 1),
('lblHideTurnThreads', 'Hide Turn Threads?', 'en', 1),
('lblNoHours', 'By # of Hours (if applicable):', 'en', 1),
('lblNoWriters', '# of Writers (if applicable):', 'en', 1),
('lblMaxWriters', 'Max Writers (optional):', 'en', 1),
('btnJoinStory', '✋ Join This Story', 'en', 1),
('txtAlreadyJoined', 'You have already joined this story!', 'en', 1),
('txtStoryJoinFail', 'You were not added to the story. Please contact an administrator.', 'en', 1),
('txtMoreWritersDelay', 'This story will begin when X more writer(s) join!', 'en', 1),
('txtStoryCreated', 'Story created successfully!', 'en', 1),
('txtMyStoriesTitle', '📚 Your Active Stories', 'en', 1),
('txtAllStories', 'All Stories', 'en', 1),
('txtJoinableStories', 'Joinable Stories', 'en', 1),
('txtMyStories', 'My Stories', 'en', 1),
('txtStoriesPageTitle', '📚 [filter_title] (Page [page]/[total_pages])', 'en', 1),
('txtStoriesPageDesc', 'Showing [showing] of [total] stories', 'en', 1),
('txtMemberStatusCanJoin', '🟢 Can Join', 'en', 1),
('txtMemberStatusCanNotJoin', '🔴 Cannot Join', 'en', 1),
('txtMemberStatusJoined', '✅ Joined', 'en', 1),
('txtStoryListFailed', 'Failed to load stories. Please try again.', 'en', 1),
('lblStoryStatus', 'Status:', 'en', 1),
('lblStoryTurn', 'Turn:', 'en', 1),
('lblStoryWriters', 'Writers:', 'en', 1),
('lblStoryMode', 'Mode:', 'en', 1),
('lblStoryCreator', 'Creator:', 'en', 1),
('txtModeQuick', 'Quick', 'en', 1),
('txtModeNormal', 'Normal', 'en', 1),
('txtModeSlow', '🔵 Slow', 'en', 1),
('txtTurnWaiting', 'Waiting to start', 'en', 1),
('txtTurnOverdue', '[writer_name] (overdue)', 'en', 1),
('txtTurnTimeLeft', '[writer_name] ([hours]h left)', 'en', 1),
('txtTurnUnknown', 'Unknown', 'en', 1),
('lblJoinPenName', 'Pen Name (optional)', 'en', 1),
('lblJoinPrivacySelect', '**Turn Thread Privacy**', 'en', 1),
('lblJoinNotifSelect', 'Notifications', 'en', 1),
('txtJoinEmbedDesc', 'Choose your preferences below, then click **Confirm Join**. You can update these later from your story settings.', 'en', 1),
('txtJoinPenNameNotSet', 'Not set — will use your Discord display name', 'en', 1),
('btnJoinSetPenName', 'Set Pen Name', 'en', 1),
('btnJoinConfirm', '✅ Confirm Join', 'en', 1),
('txtJoinSuccess', '✅ Successfully joined "[story_title]"! You are writer #[writer_number].', 'en', 1),
('txtJoinStoryFull', '❌ This story has reached its maximum of [max_writers] writers.', 'en', 1),
('txtJoinNotAllowed', '❌ This story does not allow new writers to join after it has started.', 'en', 1),
('txtJoinStoryClosed', '❌ This story is closed and not accepting new writers.', 'en', 1),
('txtJoinFormFailed', 'Failed to open join form. Please try again.', 'en', 1),
('txtJoinProcessFailed', 'Failed to process join request. Please try again.', 'en', 1),
('txtJoinPrivacyPlaceholder', 'Enter: public or private', 'en', 1),
('txtJoinNotificationPlaceholder', 'Enter: dm or mention', 'en', 1),
('txtJoinPenNamePlaceholder', 'Leave blank to use Discord display name', 'en', 1),
('txtCreateStoryTitle', 'Create New Story', 'en', 1),
('txtStoryAddIntro', 'Configure your story settings with the buttons below, then click Create Story when ready.', 'en', 1),
('txtStoryTitlePrompt', '⚠️ *Required — click below to set Story Title*', 'en', 1),
('txtHideThreadsOffDesc', 'Turn threads are public.', 'en', 1),
('txtHideThreadsOnDesc', 'Turn threads are private.', 'en', 1),
('txtStoryAddSessionExpired', 'Your story creation session has expired. Please run /story add again.', 'en', 1),
('btnSetTitle', 'Set Story Title', 'en', 1),
('btnAddTitleAndSummary', 'Title, Summary, & Scene Break', 'en', 1),
('btnAddSettings', 'Story Settings', 'en', 1),
('btnAddMetadata', 'Story Metadata', 'en', 1),
('btnAddTags', 'Story Tags', 'en', 1),
('btnAddMySettings', 'My Join Settings', 'en', 1),
('btnCreateStory', '✅ Create Story', 'en', 1),
('lblModeToggle', 'Story Mode', 'en', 1),
('lblHideToggle', 'Hide Threads', 'en', 1),
('btnAddHideToggle', 'Hide Turn Threads', 'en', 1),
('lblPrivateToggle', 'Turns', 'en', 1),
('lblDelayStart', 'Delay Start By', 'en', 1),
('txtDelayHint', 'leave blank for no start delay', 'en', 1),
('lblWriterOrder', 'Writer Order', 'en', 1),
('lblShowAuthors', 'Show Names', 'en', 1),
('txtShowAuthorsOnDesc', 'Shows writer names with entries.', 'en', 1),
('txtShowAuthorsOffDesc', 'Entries are anonymous.', 'en', 1),
('txtOrderRandom', 'Random', 'en', 1),
('txtOrderRoundRobin', 'Round Robin', 'en', 1),
('txtOrderFixed', 'Fixed Order', 'en', 1),
('txtOrderRandomDesc', 'Completely random each turn.', 'en', 1),
('txtOrderRoundRobinDesc', 'Rotates randomly, with no repeats.', 'en', 1),
('txtOrderFixedDesc', 'Turns follow join order.', 'en', 1),
('lblJoinNotifications', '**Notification Preference:**', 'en', 1),
('lblJoinPrivacy', '**Turn Thread Privacy:**', 'en', 1),
('txtAddValidationTitleEmpty', 'Story title cannot be empty.', 'en', 1),
('txtAddValidationTitleRequired', 'Please set a story title before creating the story.', 'en', 1),
('txtListFilterPrompt', '🔍 **Filter stories:**', 'en', 1),
('txtStoryAddSectionBreakSettings', '**⚙️ Story Settings**', 'en', 1),
('txtStoryAddSectionBreakMeta', '**🗂️ Story Metadata**', 'en', 1),
('txtStoryAddSectionBreakJoin', '**🖊️ My Join Settings**', 'en', 1),
-- close.js: confirmation reply after successful story close
('txtStoryCloseSuccess', '✅ Story closed.', 'en', 1),
-- join.js: pen name modal title
('lblJoinSetPenNameModalTitle', 'Set Pen Name', 'en', 1),
-- timeleft.js: embed field labels and hidden-authors placeholder
('lblTimeleftStory', 'Story', 'en', 1),
('lblTimeleftCurrentWriter', 'Current Writer', 'en', 1),
('lblTimeleftTurnEnds', 'Turn Ends', 'en', 1),
('lblTimeleftUpNext', 'Up Next', 'en', 1),
('txtTimeleftAuthorsHidden', '*(hidden)*', 'en', 1),
-- edit.js: pagination and edit UI strings
('lblEditPageSplitNotice', '📄 Entry split across pages', 'en', 1),
('txtEditPageSplitInstructions', 'Edits on this page do not affect other pages in the entry.\nUse ← Prev / Next → to navigate the full entry.', 'en', 1),
('btnEditPrev', '← Prev', 'en', 1),
('btnEditNext', 'Next →', 'en', 1),
('btnEditOpen', 'Edit', 'en', 1),
('btnEditHistory', 'History', 'en', 1),
('lblEditEntryContent', 'Entry content', 'en', 1),
('txtEditRestoreWarningMulti', '*This version spans multiple pages. Restoring will replace your entire current entry and will alter the story''s turn count.*', 'en', 1),
('txtEditRestoreWarningSingle', '*Restoring will replace your entire current entry and will alter the story''s turn count.*', 'en', 1),
('btnEditHistNewer', '← Newer', 'en', 1),
('btnEditHistPrevPage', '← Prev Page', 'en', 1),
('btnEditRestore', 'Restore This Version', 'en', 1),
('btnEditHistNextPage', 'Next Page →', 'en', 1),
('btnEditHistOlder', 'Older →', 'en', 1),
('btnEditBackToEntry', '← Back to Entry', 'en', 1),
('txtEditRestoreConfirmSingle', 'Restore this entry to the story? It will reappear in `/story read` and exports, and will alter the story''s turn count.', 'en', 1),
('txtEditRestoreConfirmMulti', 'Restore this version? This will replace your entire current entry, including content not shown on this page, and will alter the story''s turn count.', 'en', 1),
('txtEditRestoreConfirmTitle', 'Confirm Restore', 'en', 1),
('btnEditRestoreConfirm', 'Confirm Restore', 'en', 1),
('btnEditRestoreCancel', 'Cancel', 'en', 1),
-- Moved from config_other: story join/manage display keys
('lblKeepYourPrivate', 'Keep your turn threads private?:', 'en', 1),
('txtStoryAlreadyClosed', 'This story is already closed.', 'en', 1),
('txtStoryFeedJoinAnnouncement', '🎭 **[joiner_name]** just joined **[story_title]**! It''s currently **[current_writer]**''s turn until [turn_end_date].', 'en', 1),
('txtStoryFeedJoinAnnouncementNoTurn', '🎭 **[joiner_name]** just joined **[story_title]**!', 'en', 1),
('txtStoryFeedJoinAnnouncementSlow', '🔵 **[joiner_name]** just joined **[story_title]**! It''s currently **[current_writer]**''s turn (no turn timer).', 'en', 1),
('txtStoryFeedNowActive', '🎬 **[story_title] is now active!** [first_writer] will start the story. Turn ends [turn_end_date].', 'en', 1),
('txtStoryFeedNowActiveSlow', '🔵 **[story_title] is now active!** [first_writer] will start the story (no turn timer).', 'en', 1),
('txtPrivacyValidation', 'Keep Private must be "yes" or "no".', 'en', 1),
('txtManageStoryStatusActive', '▶️ Active', 'en', 1),
('txtManageStoryStatusPaused', '⏸️ Paused', 'en', 1),
('txtManageJoinOpen', '🔓 Open', 'en', 1),
('txtManageJoinClosed', '🔒 Closed', 'en', 1),
('lblManageSetTitleField', 'New Title', 'en', 1),
('lblManageEntriesFilterField', 'Name fragment (partial match)', 'en', 1),
-- Silo 4: manage modal placeholders
('txtManageMaxWritersPlaceholder', 'Enter a number, or leave blank for no limit', 'en', 1),
('txtManageTagsPlaceholder', 'Comma-separated tags (e.g. fluff, AU, slow burn)', 'en', 1);