-- Context: config_mystory
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('lblYourAO3Name', 'Your Pen Name:', 'en', 1),
('txtMyStoryNone', '🤷 You''re not currently a writer in any active stories. Use /story join to get started!', 'en', 1),
('txtMyTurnQuick', '🎯 **Your turn!** Use `/story write [story_id]`', 'en', 1),
('txtMyTurnNormal', '🎯 **Your turn!**', 'en', 1),
('txtOthersTurn', '✍️ [writer_name]''s turn', 'en', 1),
('txtMyTurnHistory', '↩️ Last turn [last_turn_at] · [turn_count] turn(s)', 'en', 1),
('txtMyTurnNoHistory', '↩️ No turns yet', 'en', 1),
('txtCatchupNoEntries', 'No new entries since your last turn.', 'en', 1),
('txtCatchupSessionExpired', 'Session expired. Please run `/mystory catchup` again.', 'en', 1),
('txtMyStoryManageTitle', 'My Settings — **[story_title]**', 'en', 1),
('lblMyStoryManageAO3', 'Pen Name', 'en', 1),
('lblMyStoryManageNotif', 'Notifications', 'en', 1),
('lblMyStoryManagePrivacy', 'Turn Privacy', 'en', 1),
('txtMyStoryManageSaved', '✅ Your settings have been saved.', 'en', 1),
('btnMyStoryManageSave', '✅ Save Changes', 'en', 1),
('txtLeaveConfirm', '⚠️ Are you sure you want to leave **[story_title]**? This cannot be undone.', 'en', 1),
('txtLeaveConfirmMyTurn', '⚠️ It''s currently your turn in **[story_title]**. Leaving will skip your turn. Are you sure?', 'en', 1),
('txtLeaveConfirmLastWriter', '⚠️ You are the **last active writer** in **[story_title]**. Leaving will automatically close the story. Are you sure?', 'en', 1),
('txtLeftStorySuccess', '✅ You have left the story.', 'en', 1),
('txtPassSuccess', '✅ Your turn has been passed.', 'en', 1),
('txtAO3NamePlaceholder', 'Your pen name (optional)', 'en', 1),
('txtMyListTitle', '📚 Your Stories (Page [page]/[total])', 'en', 1),
('txtMyListNone', 'You have no story history yet. Use `/story join` to get started!', 'en', 1),
('btnMyStoryManagePause', '⏸️ Pause Participation', 'en', 1),
('btnMyStoryManageResume', '▶️ Resume Participation', 'en', 1),
('btnMyStoryManagePass', '⏭️ Pass My Turn', 'en', 1),
('btnMyStoryManageLeave', '🚪 Leave Story', 'en', 1),
('lblMyStoryManageStatus', 'Status', 'en', 1),
('txtMyStoryManagePausedStatus', 'Paused', 'en', 1),
('txtMyStoryManageActiveStatus', 'Active', 'en', 1),
('txtMyPassConfirm', '⏭️ **Pass your turn in [story_title]?** This will skip to the next writer without submitting an entry. This cannot be undone.', 'en', 1),
('txtMyPauseConfirm', '⏸️ **Pause your participation in [story_title]?** You will be removed from the turn rotation. If it is currently your turn, it will be passed automatically. Use Resume to rejoin.', 'en', 1),
('txtMyResumeSuccess', '▶️ You have rejoined the rotation for **[story_title]**.', 'en', 1),
('txtMyPauseSuccess', '⏸️ You have been paused in **[story_title]**.', 'en', 1),
('txtMyPassSuccess', '✅ Your turn has been passed.', 'en', 1),
-- Moved from config_other: mystory-specific keys
('btnLeaveStory', 'Leave Story', 'en', 1),
('txtMyHelpTitle', '📋 Writer Command Reference', 'en', 1),
('txtMyHelpFooter', 'For story creation, modes, and settings — use /story help', 'en', 1),
('lblMyHelpDashboard', '📊 Your Dashboard', 'en', 1),
('txtMyHelpDashboard', '- `/mystory list` — See all your stories — active, paused, delayed, and closed\n- `/mystory catchup [id]` — Read entries written since your last turn', 'en', 1),
('lblMyHelpPause', '⏸️ Pausing', 'en', 1),
('txtMyHelpPause', '- Use the **Pause** button in `/mystory manage [id]` to step out of the turn rotation temporarily. If it''s your turn when you pause, it will be passed automatically.\n- Use **Resume** to rejoin the rotation. You''ll re-enter the order of writers as before, depending on story settings.', 'en', 1),
('btnMyPassConfirm', 'Yes, Pass My Turn', 'en', 1),
('btnMyPauseConfirm', 'Yes, Pause', 'en', 1),
('lblMyNotifications', 'DM Notifications', 'en', 1),
('lblMyHelpTurn', '✍️ Your Turn', 'en', 1),
('txtMyHelpTurn', '- `/story write [id]` — Submit your entry *(quick mode)*\n- `/story read [id]` — Read the story in Discord\n- `/story edit [id]` — Edit one of your finalized entries\n- `/mystory manage [id]` — Pass your turn, pause, or leave a story', 'en', 1),
-- Silo 4: list embed stat strings
('txtMyListJoined', 'Joined [date]', 'en', 1),
('txtMyListMyStats', 'Your turns: [turn_count] · ~[word_count] words', 'en', 1),
('txtMyListNoTurns', 'No turns yet', 'en', 1),
('txtMyListStoryTotal', 'Story total: [turn_count] turn(s)', 'en', 1),
('txtMyListPausedSuffix', '⏸ You are paused', 'en', 1),
-- Silo 4: catchup embed strings
('txtCatchupTurnHeader', 'Turn [turn_number] — [writer_name]', 'en', 1),
('txtCatchupIntro', '📖 **[story_title]** — [turn_count] turn(s) since your last turn.', 'en', 1),
('txtCatchupIntroNoTurns', '📖 **[story_title]** — [turn_count] turn(s) so far (you haven''t had a turn yet).', 'en', 1),
('txtCatchupNavHeader', '📖 **[story_title]** — (Page [page]/[total])', 'en', 1),
-- Silo 4: manage panel description
('txtMyStoryManagePanelDesc', '-# Notifications and Privacy are staged — click **Save Settings** to apply.', 'en', 1);