-- Context: config_story
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('lblStoryTitle', 'Story Title:', 'en', 1),
('lblQuickMode', 'Quick Mode?:', 'en', 1),
('lblTurnLength', 'Turn Length (hours):', 'en', 1),
('lblTimeoutReminder', 'Timeout Reminder Interval:', 'en', 1),
('lblHideTurnThreads', 'Hide Turn Threads?', 'en', 1),
('lblNoHours', 'By # of Hours (if applicable):', 'en', 1),
('lblNoWriters', '# of Writers (if applicable):', 'en', 1),
('lblMaxWriters', 'Max Writers (optional):', 'en', 1),
('btnSetMaxWriters', 'Max Writers: [max_writers]', 'en', 1),
('btnJoinStory', '✋ Join This Story', 'en', 1),
('txtAlreadyJoined', 'You have already joined this story!', 'en', 1),
('txtStoryJoinFail', 'You were not added to the story. Please contact an administrator.', 'en', 1),
('txtMoreWritersDelay', 'This story will begin when X more writer(s) join!', 'en', 1),
('txtStoryCreated', 'Story created successfully!', 'en', 1),
('txtMyStoriesTitle', '📚 Your Active Stories', 'en', 1),
('txtAllStories', 'All Stories', 'en', 1),
('txtJoinableStories', 'Joinable Stories', 'en', 1),
('txtMyStories', 'My Stories', 'en', 1),
('txtStoriesPageTitle', '📚 [filter_title] (Page [page]/[total_pages])', 'en', 1),
('txtStoriesPageDesc', 'Showing [showing] of [total] stories', 'en', 1),
('txtMemberStatusCanJoin', '🟢 Can Join', 'en', 1),
('txtMemberStatusCanNotJoin', '🔴 Cannot Join', 'en', 1),
('txtMemberStatusJoined', '✅ Joined', 'en', 1),
('txtStoryListFailed', 'Failed to load stories. Please try again.', 'en', 1),
('lblStoryStatus', 'Status:', 'en', 1),
('lblStoryTurn', 'Turn:', 'en', 1),
('lblStoryWriters', 'Writers:', 'en', 1),
('lblStoryMode', 'Mode:', 'en', 1),
('lblStoryCreator', 'Creator:', 'en', 1),
('txtModeQuick', 'Quick', 'en', 1),
('txtModeNormal', 'Normal', 'en', 1),
('txtTurnWaiting', 'Waiting to start', 'en', 1),
('txtTurnOverdue', '[writer_name] (overdue)', 'en', 1),
('txtTurnTimeLeft', '[writer_name] ([hours]h left)', 'en', 1),
('txtTurnUnknown', 'Unknown', 'en', 1),
('lblJoinAO3Name', 'Pen Name (optional)', 'en', 1),
('lblJoinPrivacySelect', 'Turn Thread Privacy', 'en', 1),
('lblJoinNotifSelect', 'Notifications', 'en', 1),
('txtJoinEmbedDesc', 'Choose your preferences below, then click **Confirm Join**. You can update these later from your story settings.', 'en', 1),
('txtJoinAO3NotSet', 'Not set — will use your Discord display name', 'en', 1),
('btnJoinSetAO3', 'Set Pen Name', 'en', 1),
('btnJoinConfirm', '✅ Confirm Join', 'en', 1),
('txtJoinSuccess', '✅ Successfully joined "[story_title]"! You are writer #[writer_number].', 'en', 1),
('txtJoinStoryFull', '❌ This story has reached its maximum of [max_writers] writers.', 'en', 1),
('txtJoinNotAllowed', '❌ This story does not allow new writers to join after it has started.', 'en', 1),
('txtJoinStoryClosed', '❌ This story is closed and not accepting new writers.', 'en', 1),
('txtJoinFormFailed', 'Failed to open join form. Please try again.', 'en', 1),
('txtJoinProcessFailed', 'Failed to process join request. Please try again.', 'en', 1),
('txtJoinPrivacyPlaceholder', 'Enter: public or private', 'en', 1),
('txtJoinNotificationPlaceholder', 'Enter: dm or mention', 'en', 1),
('txtJoinAO3Placeholder', 'Leave blank to use Discord display name', 'en', 1),
('txtCreateStoryTitle', 'Create New Story', 'en', 1),
('txtStoryAddIntro', 'Configure your story settings with the buttons below, then click Create Story when ready.', 'en', 1),
('txtStoryTitlePrompt', '⚠️ *Required — click below to set Story Title*', 'en', 1),
('txtHideThreadsOffDesc', 'Turn threads are visible to all writers.', 'en', 1),
('txtHideThreadsOnDesc', 'Turn threads are private to the current writer only.', 'en', 1),
('txtStoryAddSessionExpired', 'Your story creation session has expired. Please run /story add again.', 'en', 1),
('btnSetTitle', 'Set Story Title', 'en', 1),
('btnSetTurnLength', 'Turn Length: [turn_length]', 'en', 1),
('btnSetTimeout', 'Reminder Interval: [reminder_interval]', 'en', 1),
('btnSetAO3Name', 'Set Pen Name', 'en', 1),
('btnSetDelayHours', 'Set Delay Hours', 'en', 1),
('btnSetDelayWriters', 'Set Delay Writers', 'en', 1),
('btnCreateStory', '✅ Create Story', 'en', 1),
('lblModeToggle', 'Story Mode', 'en', 1),
('lblHideToggle', 'Hide Threads', 'en', 1),
('btnAddHideToggle', 'Hide Turn Threads', 'en', 1),
('lblPrivateToggle', 'Turns', 'en', 1),
('lblDelayStart', 'Delay Start By', 'en', 1),
('txtDelayHint', 'leave blank to start immediately', 'en', 1),
('lblWriterOrder', 'Writer Order', 'en', 1),
('lblShowAuthors', 'Show Names', 'en', 1),
('txtShowAuthorsOnDesc', 'Writer names appear on entries in Discord and in the export file.', 'en', 1),
('txtShowAuthorsOffDesc', 'Entries are posted and exported anonymously.', 'en', 1),
('txtOrderRandom', 'Random', 'en', 1),
('txtOrderRoundRobin', 'Round Robin', 'en', 1),
('txtOrderFixed', 'Fixed Order', 'en', 1),
('txtOrderRandomDesc', 'Next writer is chosen completely at random each turn.', 'en', 1),
('txtOrderRoundRobinDesc', 'Writers rotate randomly, but no one repeats until everyone has had a turn.', 'en', 1),
('txtOrderFixedDesc', 'Writers take turns in a fixed sequence based on join order.', 'en', 1),
('lblJoinNotifications', 'Notification Preference:', 'en', 1),
('lblJoinPrivacy', 'Turn Thread Privacy:', 'en', 1),
('txtAddValidationTitleEmpty', 'Story title cannot be empty.', 'en', 1),
('txtAddValidationTitleRequired', 'Please set a story title before creating the story.', 'en', 1),
('txtListFilterPrompt', '🔍 **Filter stories:**', 'en', 1),
('txtStoryAddSectionBreakSettings', '**⚙️ Story Settings**', 'en', 1),
('txtStoryAddSectionBreakMeta', '**🗂️ Story Metadata**', 'en', 1),
('txtStoryAddSectionBreakJoin', '**🖊️ My Join Settings**', 'en', 1);