-- Context: Other/Uncategorized
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('lblKeepYourPrivate', 'Keep your turn threads private?:', 'en', 1),
('btnLeaveStory', 'Leave Story', 'en', 1),
('txtStoryAlreadyClosed', 'This story is already closed.', 'en', 1),
('txtStoryCloseNotAuthorized', 'You do not have permission to close this story. Only the story creator or an admin can close a story.', 'en', 1),
('txtStoryFeedJoinAnnouncement', '🎭 **[joiner_name]** just joined **[story_title]**! It\'s currently **[current_writer]**\'s turn until [turn_end_date].', 'en', 1),
('txtStoryFeedJoinAnnouncementNoTurn', '🎭 **[joiner_name]** just joined **[story_title]**!', 'en', 1),
('txtStoryFeedNowActive', '🎬 **[story_title] is now active!** [first_writer] will start the story. Turn ends [turn_end_date].', 'en', 1),
('txtStoryFeedTurnStart', '✍️ **[story_title]:** [current_writer]''s turn has started! Turn ends [turn_end_date].', 'en', 1),
('txtValidationErrors', '**Validation Errors:**', 'en', 1),
('txtPrivacyValidation', 'Keep Private must be "yes" or "no".', 'en', 1),
('txtTimeoutReminderValidation', 'Timeout Reminder must be a number between 0 and 100.', 'en', 1),
('txtHideTurnThreadsValidation', 'Hide Turn Threads must be "off" or "on".', 'en', 1),
('txtFormOpenError', 'Failed to open story creation form. Please try again.', 'en', 1),
('txtFormProcessError', 'Failed to process form. Please try again.', 'en', 1),
('txtAdditionalOptionsError', 'Failed to show additional options form.', 'en', 1),
('txtStoryCreationError', 'Failed to create story. Please try again.', 'en', 1),
('txtTurnLengthPlaceholder', 'Enter number of hours', 'en', 1),
('txtTimeoutReminderPlaceholder', 'Enter: 0, 25, 50, or 75', 'en', 1),
('txtHideTurnThreadsPlaceholder', 'Enter: off or on', 'en', 1),
('txtDelayHoursPlaceholder', 'Enter number of hours (optional)', 'en', 1),
('txtDelayWritersPlaceholder', 'Enter number of writers (optional)', 'en', 1),
('txtKeepPrivatePlaceholder', 'Enter: yes or no', 'en', 1),
('btnHelp1ToPage2', '📝 Story Creation Guide →', 'en', 1),
('lblHelp1FindJoin', '📚 Find & Join a Story', 'en', 1),
('lblHelp1JoiningOptions', '⚙️ Joining Options', 'en', 1),
('lblHelp1Dashboard', '🗂️ Your Dashboard', 'en', 1),
('lblHelp1ManageParticipation', '🤝 Managing Your Participation', 'en', 1),
('lblHelp1WriteNormal', '✍️ Writing Your Turn — Normal Mode', 'en', 1),
('lblHelp1WriteQuick', '⚡ Writing Your Turn — Quick Mode', 'en', 1),
('btnHelp2ToPage1', '← Back to Overview', 'en', 1),
('btnHelp2ToPage3', '⚙️ Story Manage Guide →', 'en', 1),
('lblHelp2StoryTitle', 'Story Title', 'en', 1),
('lblHelp2MaxWriters', 'Max Writers', 'en', 1),
('lblHelp2TurnLength', 'Turn Length', 'en', 1),
('lblHelp2StoryMode', 'Story Mode', 'en', 1),
('lblHelp2WriterOrder', 'Writer Order', 'en', 1),
('lblHelp2HideThreads', 'Hide Threads', 'en', 1),
('lblHelp2ShowAuthors', 'Show Author Names', 'en', 1),
('lblHelp2TimeoutReminder', 'Timeout Reminder', 'en', 1),
('lblHelp2DelayStart', 'Delay Start By', 'en', 1),
('lblHelp2CreatorOptions', 'Story Creator''s Join Options', 'en', 1),
('btnHelp3ToPage2', '← Story Creation Guide', 'en', 1),
('lblHelp3WhoCanUse', 'Who can use /story manage?', 'en', 1),
('lblHelp3WhatEdit', 'What can be edited?', 'en', 1),
('lblHelp3PauseResume', 'Pausing and Resuming', 'en', 1),
('lblHelp3Closing', 'Closing a Story', 'en', 1),
('lblHelp3AdminControls', 'Admin Controls', 'en', 1),
('txtMyHelpTitle', '📋 Writer Command Reference', 'en', 1),
('txtMyHelpFooter', 'For story creation, modes, and settings — use /story help', 'en', 1),
('lblMyHelpDashboard', '📊 Your Dashboard', 'en', 1),
('txtMyHelpDashboard', '- `/mystory active` — Your active stories and whose turn it is\n- `/mystory history` — All stories you''ve ever been in\n- `/mystory catchup [id]` — Read entries written since your last turn', 'en', 1),
('lblMyHelpTurn', '✍️ Your Turn', 'en', 1),
('txtMyHelpTurn', '- `/story write [id]` — Submit your entry *(quick mode)*\n- `/story read [id]` — Read the story in Discord\n- `/story edit [id]` — Edit one of your finalized entries\n- `/mystory pass [id]` — Skip your current turn\n- `/mystory leave [id]` — Leave a story', 'en', 1),
('lblMyHelpPause', '⏸️ Pausing', 'en', 1),
('txtMyHelpPause', '- `/mystory pause [id]` — Step out of the turn rotation temporarily. Omit the ID to pause all of your active stories at once. If it''s your turn when you pause, it will be passed automatically. To leave the story permanently, use `/mystory leave [id]`.\n- `/mystory resume [id]` — Rejoin the rotation. You''ll re-enter the order of writers as before, depending on story settings.', 'en', 1),
('lblAdminHelpSkip', '/storyadmin skip [story_id]', 'en', 1),
('lblAdminHelpExtend', '/storyadmin extend [story_id] [hours]', 'en', 1),
('lblAdminHelpManageUser', '/storyadmin manage [story_id] [user]', 'en', 1),
('lblAdminHelpNext', '/storyadmin next [story_id] [user]', 'en', 1),
('lblAdminHelpReassign', '/storyadmin reassign [story_id]', 'en', 1),
('lblAdminHelpDelete', '/storyadmin delete [story_id]', 'en', 1),
('lblAdminHelpSetup', '/storyadmin setup', 'en', 1),
('txtSetupRoundupDayInvalid', '❌ Day must be a number between 0 (Sunday) and 6 (Saturday).', 'en', 1),
('txtSetupRoundupHourInvalid', '❌ Hour must be a number between 0 and 23 (UTC).', 'en', 1),
('btnAdminMUPause', '⏸️ Pause', 'en', 1),
('btnAdminMUUnpause', '▶️ Restore', 'en', 1),
('btnAdminMURemove', 'Remove', 'en', 1),
('btnAdminMUAO3Name', 'Update Name', 'en', 1),
('btnConfirmDelete', '🗑️ Permanently Delete', 'en', 1),
('txtFinalizeConfirm', 'Finalize your entry?', 'en', 1),
('txtFinalizeConfirmDesc', 'This will submit everything shown below and advance to the next writer. This cannot be undone.', 'en', 1),
('lblFinalizePreviewEntry', 'Your Entry', 'en', 1),
('txtFinalizeImageReview', 'Images in the entry will display with this text:\n*filename : display text*\n[image_list]\n\nTo change the link text, cancel the finalization and edit the image post.', 'en', 1),
('txtSkipConfirmNoContent', '⏭️ **Skip your turn?** This will pass to the next writer without submitting an entry. This cannot be undone.', 'en', 1),
('txtSkipConfirmHasContent', '⚠️ **Skip your turn?** You have posted content in this thread — **it will be discarded** if you skip. This cannot be undone.', 'en', 1),
('lblAdminHelpRemove', '/storyadmin remove [story_id] [user]', 'en', 1),
('txtReadEntryNotFound', 'Entry not found in session. Please use `/story read` again.', 'en', 1),
('txtReadSessionExpired', 'This reading session has expired. Use `/story read` again.', 'en', 1),
('cfgRestrictedFeedChannelId', '', 'en', 1),
('cfgRestrictedMediaChannelId', '', 'en', 1),
('txtSetupRestrictedChannelInvalid', '❌ Could not find the restricted feed channel with that ID. Please check and try again.', 'en', 1),
('txtSetupRestrictedMediaInvalid', '❌ Could not find the restricted media channel with that ID. Please check and try again.', 'en', 1),
('lblTagSubmitText', 'Tag to suggest', 'en', 1),
('btnMyPassConfirm', 'Yes, Pass My Turn', 'en', 1),
('btnMyPauseConfirm', 'Yes, Pause', 'en', 1),
('btnAdminMUSave', '✅ Save Settings', 'en', 1),
('lblAdminMUNotif', 'Notifications', 'en', 1),
('lblAdminMUPrivacy', 'Turn Privacy', 'en', 1),
('btnAdminMUToggleNotif', 'Toggle Notifications', 'en', 1),
('btnAdminMUTogglePrivacy', 'Toggle Turn Privacy', 'en', 1),
('lblTurnActions', 'Turn Actions', 'en', 1),
('txtTurnSkipConfirm', '⏭️ **Skip [writer_name]''s turn in [story_title]?** This will end their turn immediately and advance to the next writer.', 'en', 1),
('txtTurnExtendModalTitle', 'Extend Deadline', 'en', 1),
('lblTurnExtendHours', 'Hours to add', 'en', 1),
('txtTurnExtendPlaceholder', 'Enter number of hours (e.g. 24)', 'en', 1),
('txtTurnNextModalTitle', 'Designate Next Writer', 'en', 1),
('lblTurnNextUser', 'Discord User ID or mention', 'en', 1),
('txtTurnNextPlaceholder', 'Enter @mention or user ID', 'en', 1),
('txtTurnReassignConfirm', '↩️ **Reassign turn to [prev_writer]?** They will get a new turn immediately, then [current_writer] will go next.', 'en', 1),
('txtTurnDeleteEntryModalTitle', 'Delete Entry by Turn Number', 'en', 1),
('lblTurnDeleteEntryTurn', 'Turn number (as shown in /story read)', 'en', 1),
('txtTurnDeleteEntryPlaceholder', 'Enter turn number', 'en', 1),
('txtTurnRestoreEntryModalTitle', 'Restore Deleted Entry', 'en', 1),
('lblTurnRestoreEntryId', 'Entry ID', 'en', 1),
('txtTurnRestoreEntryPlaceholder', 'Enter entry ID (shown when entry was deleted)', 'en', 1),
('txtTurnNextSelectWrite', 'Select the writer who will receive the next turn:', 'en', 1),
('lblMyNotifications', 'DM Notifications', 'en', 1),
('txtManageStoryStatusActive', '▶️ Active', 'en', 1),
('txtManageStoryStatusPaused', '⏸️ Paused', 'en', 1),
('txtManageJoinOpen', '🔓 Open', 'en', 1),
('txtManageJoinClosed', '🔒 Closed', 'en', 1),
('lblManageSetTitleField', 'New Title', 'en', 1),
('lblManageEntriesFilterField', 'Name fragment (partial match)', 'en', 1),
('txtManageEntryDeleteSuccess', '✅ Entry deleted. Entry ID: **[entry_id]** (use Restore Entry to undo).', 'en', 1),
('txtManageEntryRestoreSuccess', '✅ Entry restored for **[writer_name]**.', 'en', 1),
('txtManageEntryAlreadyDeleted', '❌ This entry is already deleted.', 'en', 1),
('txtManageEntryAlreadyConfirmed', '❌ This entry is not deleted.', 'en', 1),
('lblHelp2Metadata', '📋 Story Metadata', 'en', 1);