-- Context: config_system
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('txtYes', 'Yes', 'en', 1),
('txtNo', 'No', 'en', 1),
('txtOn', 'On', 'en', 1),
('txtOff', 'Off', 'en', 1),
('txtNone', 'None', 'en', 1),
('txtPublic', 'Public', 'en', 1),
('txtPrivate', 'Private', 'en', 1),
('txtOpen', 'Open', 'en', 1),
('txtClosed', 'Closed', 'en', 1),
('txtActive', 'Active', 'en', 1),
('txtPaused', 'Paused', 'en', 1),
('txtDelayed', 'Delayed', 'en', 1),
('txtNotSet', 'Not Set', 'en', 1),
('txtInfinity', '∞', 'en', 1),
('txtUnknownWriter', 'Unknown', 'en', 1),
('txtStory', 'Story', 'en', 1),
('txtPause', 'Pause', 'en', 1),
('txtResume', 'Resume', 'en', 1),
('txtHrs', 'hrs', 'en', 1),
('txtHoursLC', 'hours', 'en', 1),
('txtHoursUC', 'Hours', 'en', 1),
('txtWritersLC', 'writers', 'en', 1),
('txtWritersUC', 'Writers', 'en', 1),
('txtQuickLC', 'quick', 'en', 1),
('txtQuickUC', 'Quick', 'en', 1),
('txtNormalLC', 'normal', 'en', 1),
('txtNormalUC', 'Normal', 'en', 1),
('txtSlowTC', 'Slow', 'en', 1),
('txtSlowLC', 'slow', 'en', 1),
('txtNA', 'N/A', 'en', 1),
('txtSlowModeDesc', 'Writers get a turn thread with no time limit. Turns advance when skipped or finalized.', 'en', 1),
('txtNormalModeWelcome', '## Welcome to your turn thread for *[story_title]*\nWrite your story entry here in as many posts as you''d like. Edit as needed, and use Discord markdown for formatting. Use the buttons below to Finalize your turn, or Skip to pass to the next writer without submitting.\n\nYour turn ends on [turn_end_full], [turn_end_relative]. If you need to catch up with the story since your last turn, use the command `/mystory catchup story_id:[story_id]`.', 'en', 1),
('txtNormalModeWelcomeNoMedia', '## Welcome to your turn thread for *[story_title]*\nWrite your story entry here in as many posts as you''d like. Edit as needed, using Discord markdown for formatting. Use the buttons below to Finalize your turn, or Skip to pass to the next writer without submitting.\n\nYour turn ends on [turn_end_full], [turn_end_relative]. If you need to catch up with the story since your last turn, use the command `/mystory catchup story_id:[story_id]`.', 'en', 1),
('txtQuickModeTurnStart', '🎭 **[story_title]:** [current_writer]''s turn has started! Please use `/story write [story_id]` to submit your entry. Turn ends [turn_end_date].', 'en', 1),
('txtHoursDelay', 'This story will begin in X hours!', 'en', 1),
('txtNormalModeWrite', 'This story is in normal mode. Please write your entry in your private turn thread.', 'en', 1),
('txtNotYourTurn', 'It is not your turn to write. Please wait for your turn.', 'en', 1),
('btnSubmit', 'Submit', 'en', 1),
('btnDiscard', 'Discard', 'en', 1),
('txtActionFailed', 'Failed to process action. Please try again.', 'en', 1),
('txtNoActiveTurn','You do not have an active turn in this story.', 'en', 1),
('btnCancel', 'Cancel', 'en', 1),
('txtDelete', 'Delete', 'en', 1),
('txtApproved', 'Approved', 'en', 1),
('txtRejected', 'Rejected', 'en', 1),
('txtActionCancelled', 'Cancelled.', 'en', 1),
('txtActionSessionExpired', 'Your session has expired. Please try again.', 'en', 1),
('txtNotActiveWriter', 'You are not an active writer in this story.', 'en', 1),
('txtNoConfirmedEntries', 'This story has no finalized entries yet.', 'en', 1),
('txtNoActiveStoriesToPause', 'You are not an active writer in any stories right now.', 'en', 1),
('txtPauseSuccess', '✅ You have been paused. Check your DMs for a summary.', 'en', 1),
('txtPauseDM', 'You have been paused in the following stories:\n[story_list]\n\nWhen you''re ready to jump back in, use [resume_command]. Note that pausing does not remove you from the story — to leave permanently, use /mystory leave.', 'en', 1),
('txtResumeSuccess', '✅ You are back in the rotation. You will be included in the selection of writers the next time a turn starts.', 'en', 1),
('txtNotPaused', 'You are not currently paused in any stories.', 'en', 1),
('txtActiveStories', 'Active Stories', 'en', 1),
('txtPausedStories', 'Paused Stories', 'en', 1),
('txtNoStoriesFound', '📚 **No stories found** for filter "[filter_name]"', 'en', 1),
('txtQuickModeValidation', 'Quick Mode must be "off" or "on".', 'en', 1),
('txtNotificationValidation', 'Notification Preference must be "dm" or "mention".', 'en', 1),
('txtQuickModePlaceholder', 'Enter: off or on', 'en', 1),
('btnPrev', '◀️ Prev', 'en', 1),
('btnNext', 'Next ▶️', 'en', 1),
('btnFilter', '🔍 Filter', 'en', 1),
('txtQuickJoinPlaceholder', 'Quick join a story...', 'en', 1),
('txtQuickJoinDesc', '[writer_count]/[max_writers] writers • [mode] mode', 'en', 1),
('txtNormalModeDesc', 'Writers get a private or public thread for each turn.', 'en', 1),
('txtQuickModeDesc', 'Writers submit entries via the /story write command.', 'en', 1),
('txtPrivateOffDesc', 'Your turn threads will be visible to other writers.', 'en', 1),
('txtPrivateOnDesc', 'Your turn threads will only be visible to you and admins.', 'en', 1),
('txtHelp1Title', '📖 Round Robin StoryBot Overview', 'en', 1),
('txtHelp1Footer', 'Page 1 of 3 · Story IDs appear in /story list and in story thread titles.', 'en', 1),
('txtHelp1FindJoin', 'Use `/story list` to browse all of the stories on the server, past or present. Stories have dedicated threads for all of their activity, and those can be found by clicking the 🧵 icon in the Round Robin feed channel.\n\nWhen you''re ready, you can join a story in several ways:\n- Use the quick join menu on `/story list`\n- Type `/story join [id]`\n- Navigate to the story thread and click the "✍️ Join This Story" button on the pinned story info post at the top of the thread.', 'en', 1),
('txtHelp1JoiningOptions', '**Turn Thread Privacy** *(only applies to Normal Mode stories)*\n- 🌐 **Public** — Threads for your turns will be visible to all members of your server.\n- 🔒 **Private** — Turn threads will be private and only visible to you and server admins.\n\n**Notifications**\n- 💬 **DM** — StoryBot will send you a DM for turn start, reminders, and turn timeout or skip.\n- 📢 **Mention in channel** — You will be tagged in messages from the bot posted in the story thread.\n\n**Pen Name** *(optional)*\n- ✍️ The name that will appear on the list of writers on the story. If the story is configured to display names, it will also show on entries and in the exported story. This field fills in your Discord display name by default.', 'en', 1),
('txtHelp1Dashboard', 'Use `/mystory list` to see all the stories you''ve joined — active, paused, delayed, and closed.', 'en', 1),
('txtHelp1ManageParticipation', 'Use `/mystory manage` to take action on a specific story:\n- Pass your current turn\n- Pause or resume your participation\n- Leave the story', 'en', 1),
('txtHelp1WriteNormal', 'When it''s your turn, you''ll be notified with a link to your turn thread. Type as many posts as you like, add images in their own posts with display (alt) text (if images are enabled on your server), and format your posts using Discord markdown for bold, italics, etc. If you want to review the entries in the story since you last wrote, use `/mystory catchup` to see your last entry and the entries since.\n\nYour entry won''t be posted until you click Finalize — you can revise as much as you like first. *All* of your posts in the turn thread will be compiled for your entry, so make sure you delete any of your own chatter before finalizing. Posts from the bot or other users will not be included. If you need more time, you can click a button on the first post in the thread to request an extension from the story creator.', 'en', 1),
('txtHelp1WriteNormalNoMedia', 'When it''s your turn, you''ll be notified with a link to your turn thread. Type as many posts as you like and format your posts using Discord markdown for bold, italics, etc. If you want to review the entries in the story since you last wrote, use `/mystory catchup` to see your last entry and the entries since.\n\nYour entry won''t be posted until you click Finalize — you can revise as much as you like first. *All* of your posts in the turn thread will be compiled for your entry, so make sure you delete any of your own chatter before finalizing. Posts from the bot or other users will not be included. If you need more time, you can click a button on the first post in the thread to request an extension from the story creator.', 'en', 1),
('txtHelp1WriteQuick', 'If a story is in Quick Mode, you won''t get a thread for your turn. You can post an entry by typing `/story write`. Entries are limited to 4,000 characters, and images are not supported. Your entry is posted immediately when you submit — there''s no draft or finalize step.', 'en', 1),
('txtHelp2Title', '📝 Create New Story — Option Reference', 'en', 1),
('txtHelp2Footer', 'Page 2 of 3 · After story creation, these settings can be edited by admins or the story creator via `/story manage.`', 'en', 1),
('txtHelp2StoryTitle', '- ⚠️ *Required.*', 'en', 1),
('txtHelp2MaxWriters', '- #️⃣ Optional. Leave blank for no limit.', 'en', 1),
('txtHelp2TurnLength', '- ⌛ How many hours each writer has per turn. Default: 24h.', 'en', 1),
('txtHelp2StoryMode', '- 🟢 **Normal** — Writers get a private or public thread for each turn.\n- 🟣 **Quick** — Writers submit entries via `/story write`.', 'en', 1),
('txtHelp2WriterOrder', '- 🎲 **Random** — Next writer chosen completely at random each turn.\n- 🔄 **Round Robin** — Rotates randomly, but no one repeats until everyone has had a turn.\n- 📋 **Fixed Order** — Writers take turns in a fixed sequence based on join order.', 'en', 1),
('txtHelp2HideThreads', '- 🥷 **On** — Turn threads are private to the current writer and admins only.\n- 🤡 **Off** — Turn threads are visible to all server members.', 'en', 1),
('txtHelp2ShowAuthors', '- 📑 **Yes** — Writer names appear on entries in Discord and in the export file.\n- 📄 **No** — Entries are posted and exported anonymously.', 'en', 1),
('txtHelp2TimeoutReminder', '- ⏰ Send a reminder to the current writer after X% of their turn has elapsed. Default: 50%. Set to 0% to disable.', 'en', 1),
('txtHelp2DelayStart', '- 🫸 Leave blank to start immediately. Set a number of hours, a minimum writer count, or both — the story activates when all conditions are met.', 'en', 1),
('txtHelp2CreatorOptions', '**Your Pen Name**\n- ✍️ Your name as it will appear on the story. Used in story exports. Defaults to your Discord display name if left blank.\n\n**Keep My Turns Private**\n- 🔒 **Yes** — Your turn threads will only be visible to you and admins.\n- 🔓 **No** — Your turn threads will be visible to other writers.', 'en', 1),
('txtHelp3Title', '⚙️ Managing a Story — /story manage', 'en', 1),
('txtHelp3Footer', 'Page 3 of 3', 'en', 1),
('txtHelp3WhoCanUse', 'The story creator (the first writer to join) and server admins.', 'en', 1),
('txtHelp3WhatEdit', '**Story settings** (via `/story manage`):\n- **Turn Length** — How many hours each writer has per turn.\n- **Timeout Reminder** — What % into a turn to send the writer a reminder. Set to 0% to disable.\n- **Max Writers** — Cap on total writers. Leave blank for no limit.\n- **Open to New Writers** — Allows new writers to join.\n- **Show Author Names** — Writer names appear on entries and in the story export if enabled.\n- **Writer Order** — Choose between Random, Round Robin, and Fixed (Join) Order.\n- **Turn Privacy** — Private turns are only visible to the current writer (and admins via channel permissions). Public turns are visible to all.\n- **Summary** — A freeform description used in story exports.\n- **Tags** — Comma-separated tag list used in story exports.\n\n**Entry content** — Use `/story edit [id]` to edit the text of a finalized entry. Writers can edit their own entries; admins can edit any.', 'en', 1),
('txtHelp3PauseResume', '- Sets the story status to paused (freezing the current turn) or resumes a paused story. Resuming starts the next turn automatically if no turn is currently active.\n- Use the button in `/story manage` to pause or resume.', 'en', 1),
('txtHelp3Closing', '- Use `/story close [id]` to permanently close a story. This posts a completion message with the full story export and ends the current turn, but leaves the story thread open for discussion. This cannot be undone.', 'en', 1),
('txtHelp3AdminControls', '- Skip the current turn\n- Extend the current turn\n- Set the writer who will be selected when the next turn starts\n- Remove a writer from a story\n- Delete a story', 'en', 1),
('txtNormalModeImageHelp', '📸 **Attaching images:** Upload each image in its own **separate post** in this thread in the order you would like it to appear in the story. The text of that post will become the image''s display label when the story is read. If a post has no text, the filename will be used as the label.', 'en', 1),
('cfgLanguageCode', 'en', 'en', 1),
('cfgEntryTimeoutMinutes', '10', 'en', 1),
('errProcessingRequest', 'An error occurred while processing your request.', 'en', 1),
('btnSubmitTag', '🏷️ Suggest a Tag', 'en', 1),
('btnSaveSettings', '✅ Save Settings', 'en', 1),
('btnSubmitTagRead', '🏷️ Submit Tag', 'en', 1),
('cfgHubServerId', '1498673027720679635', 'en', 1),
('cfgHubFaqChannelId', '1499454495044927739', 'en', 1),
('cfgFaqThreadOverview', '', 'en', 1),
('cfgFaqThreadWriterCmds', '', 'en', 1),
('cfgFaqThreadStoryCreation', '', 'en', 1),
('cfgFaqThreadManaging', '', 'en', 1),
('cfgFaqThreadAdminCmds', '', 'en', 1),
('txtSectionBreakLine', '═══════════════', 'en', 1),
-- Moved from config_other: /story help page UI keys
('btnHelp1ToPage2', '📝 Story Creation Guide →', 'en', 1),
('lblHelp1FindJoin', '📚 Find & Join a Story', 'en', 1),
('lblHelp1JoiningOptions', '⚙️ Joining Options', 'en', 1),
('lblHelp1Dashboard', '🗂️ Your Dashboard', 'en', 1),
('lblHelp1ManageParticipation', '🤝 Managing Your Participation', 'en', 1),
('lblHelp1WriteNormal', '✍️ Writing Your Turn — Normal Mode', 'en', 1),
('lblHelp1WriteQuick', '⚡ Writing Your Turn — Quick Mode', 'en', 1),
('btnHelp2ToPage1', '← Back to Overview', 'en', 1),
('btnHelp2ToPage3', '⚙️ Story Manage Guide →', 'en', 1),
('lblHelp2StoryTitle', 'Story Title', 'en', 1),
('lblHelp2MaxWriters', 'Max Writers', 'en', 1),
('lblHelp2TurnLength', 'Turn Length', 'en', 1),
('lblHelp2StoryMode', 'Story Mode', 'en', 1),
('lblHelp2WriterOrder', 'Writer Order', 'en', 1),
('lblHelp2HideThreads', 'Hide Threads', 'en', 1),
('lblHelp2ShowAuthors', 'Show Author Names', 'en', 1),
('lblHelp2TimeoutReminder', 'Timeout Reminder', 'en', 1),
('lblHelp2DelayStart', 'Delay Start By', 'en', 1),
('lblHelp2CreatorOptions', 'Story Creator''s Join Options', 'en', 1),
('lblHelp2Metadata', '📋 Story Metadata', 'en', 1),
('btnHelp3ToPage2', '← Story Creation Guide', 'en', 1),
('lblHelp3WhoCanUse', 'Who can use /story manage?', 'en', 1),
('lblHelp3WhatEdit', 'What can be edited?', 'en', 1),
('lblHelp3PauseResume', 'Pausing and Resuming', 'en', 1),
('lblHelp3Closing', 'Closing a Story', 'en', 1),
('lblHelp3AdminControls', 'Admin Controls', 'en', 1),
('txtHelp2Metadata', 'Optional AO3-style metadata set via the **Metadata** button in the story create form:\n- 🔞 **Rating** — G, T, M, E, or Not Rated. Affects which feed channel the story posts to.\n- ⚠️ **Warnings** — Select all that apply.\n- 📊 **Dynamic** — General, F/F, F/M, M/M, Polyamory, or Other.\n- 💞 **Main Relationship** — Primary ship or pairing (e.g. Bilbo Baggins/Thorin Oakenshield).\n- 🫂 **Other Relationships** — Additional pairings or relationships.\n- 🧑 **Characters** — Characters featured in the story.\n- 🏷️ **Tags** — Freeform tags (e.g. slow burn, hurt/comfort, AU).', 'en', 1);