-- Context: config_system
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('txtYes', 'Yes', 'en', 1),
('txtNo', 'No', 'en', 1),
('txtOn', 'On', 'en', 1),
('txtOff', 'Off', 'en', 1),
('txtNone', 'None', 'en', 1),
('txtPublic', 'Public', 'en', 1),
('txtPrivate', 'Private', 'en', 1),
('txtOpen', 'Open', 'en', 1),
('txtClosed', 'Closed', 'en', 1),
('txtActive', 'Active', 'en', 1),
('txtPaused', 'Paused', 'en', 1),
('txtDelayed', 'Delayed', 'en', 1),
('txtNotSet', 'Not Set', 'en', 1),
('txtInfinity', '∞', 'en', 1),
('txtUnknownWriter', 'Unknown', 'en', 1),
('txtStory', 'Story', 'en', 1),
('txtPause', 'Pause', 'en', 1),
('txtResume', 'Resume', 'en', 1),
('txtHrs', 'hrs', 'en', 1),
('txtHoursLC', 'hours', 'en', 1),
('txtHoursUC', 'Hours', 'en', 1),
('txtWritersLC', 'writers', 'en', 1),
('txtWritersUC', 'Writers', 'en', 1),
('txtQuickLC', 'quick', 'en', 1),
('txtQuickUC', 'Quick', 'en', 1),
('txtNormalLC', 'normal', 'en', 1),
('txtNormalUC', 'Normal', 'en', 1),
('txtSlowTC', 'Slow', 'en', 1),
('txtSlowLC', 'slow', 'en', 1),
('txtNA', 'N/A', 'en', 1),
('txtSlowModeDesc', 'Writers get a turn thread with no time limit. Turns advance when skipped or finalized.', 'en', 1),
('txtNormalModeWelcome', '## Welcome to your turn thread for *[story_title]*\nWrite your story entry here in as many posts as you''d like. Edit as needed, and use Discord markdown for formatting. Use the buttons below to Finalize your turn, or Skip to pass to the next writer without submitting.\n\nYour turn ends on [turn_end_full], [turn_end_relative]. If you need to catch up with the story since your last turn, use the command `/mystory catchup story_id:[story_id]`.', 'en', 1),
('txtNormalModeWelcomeNoMedia', '## Welcome to your turn thread for *[story_title]*\nWrite your story entry here in as many posts as you''d like. Edit as needed, using Discord markdown for formatting. Use the buttons below to Finalize your turn, or Skip to pass to the next writer without submitting.\n\nYour turn ends on [turn_end_full], [turn_end_relative]. If you need to catch up with the story since your last turn, use the command `/mystory catchup story_id:[story_id]`.', 'en', 1),
('txtQuickModeTurnStart', '🎭 **[story_title]:** [current_writer]''s turn has started! Please use `/story write [story_id]` to submit your entry. Turn ends [turn_end_date].', 'en', 1),
('txtHoursDelay', 'This story will begin in X hours!', 'en', 1),
('txtNormalModeWrite', 'This story is in normal mode. Please write your entry in your private turn thread.', 'en', 1),
('txtNotYourTurn', 'It is not your turn to write. Please wait for your turn.', 'en', 1),
('btnSubmit', 'Submit', 'en', 1),
('btnDiscard', 'Discard', 'en', 1),
('txtActionFailed', 'Failed to process action. Please try again.', 'en', 1),
('txtNoActiveTurn','You do not have an active turn in this story.', 'en', 1),
('btnCancel', 'Cancel', 'en', 1),
('txtDelete', 'Delete', 'en', 1),
('txtApproved', 'Approved', 'en', 1),
('txtRejected', 'Rejected', 'en', 1),
('txtActionCancelled', 'Cancelled.', 'en', 1),
('txtActionSessionExpired', 'Your session has expired. Please try again.', 'en', 1),
('txtNotActiveWriter', 'You are not an active writer in this story.', 'en', 1),
('txtNoConfirmedEntries', 'This story has no finalized entries yet.', 'en', 1),
('txtNoActiveStoriesToPause', 'You are not an active writer in any stories right now.', 'en', 1),
('txtPauseSuccess', '✅ You have been paused. Check your DMs for a summary.', 'en', 1),
('txtPauseDM', 'You have been paused in the following stories:\n[story_list]\n\nWhen you''re ready to jump back in, use [resume_command]. Note that pausing does not remove you from the story — to leave permanently, use /mystory leave.', 'en', 1),
('txtResumeSuccess', '✅ You are back in the rotation. You will be included in the selection of writers the next time a turn starts.', 'en', 1),
('txtNotPaused', 'You are not currently paused in any stories.', 'en', 1),
('txtActiveStories', 'Active Stories', 'en', 1),
('txtPausedStories', 'Paused Stories', 'en', 1),
('txtNoStoriesFound', '📚 **No stories found** for filter "[filter_name]"', 'en', 1),
('txtQuickModeValidation', 'Quick Mode must be "off" or "on".', 'en', 1),
('txtNotificationValidation', 'Notification Preference must be "dm" or "mention".', 'en', 1),
('txtQuickModePlaceholder', 'Enter: off or on', 'en', 1),
('btnPrev', '◀️ Prev', 'en', 1),
('btnNext', 'Next ▶️', 'en', 1),
('btnFilter', '🔍 Filter', 'en', 1),
('txtQuickJoinPlaceholder', 'Quick join a story...', 'en', 1),
('txtQuickJoinDesc', '[writer_count]/[max_writers] writers • [mode] mode', 'en', 1),
('txtNormalModeDesc', 'Writers get a private or public thread for each turn.', 'en', 1),
('txtQuickModeDesc', 'Writers submit entries via the /story write command.', 'en', 1),
('txtPrivateOffDesc', 'Your turn threads will be visible to other writers.', 'en', 1),
('txtPrivateOnDesc', 'Your turn threads will only be visible to you and admins.', 'en', 1),
('txtNormalModeImageHelp', '📸 **Attaching images:** Upload each image in its own **separate post** in this thread in the order you would like it to appear in the story. The text of that post will become the image''s display label when the story is read. If a post has no text, the filename will be used as the label.', 'en', 1),
('cfgLanguageCode', 'en', 'en', 1),
('cfgEntryTimeoutMinutes', '10', 'en', 1),
('errProcessingRequest', 'An error occurred while processing your request.', 'en', 1),
('btnSubmitTag', '🏷️ Suggest a Tag', 'en', 1),
('btnSaveSettings', '✅ Save Settings', 'en', 1),
('btnSubmitTagRead', '🏷️ Submit Tag', 'en', 1),
('cfgHubServerId', '1498673027720679635', 'en', 1),
('cfgHubFaqChannelId', '1499454495044927739', 'en', 1),
('cfgHubLogChannelId', '1505941432370724864', 'en', 1),
('cfgFaqPostIds', '1503509386520166450|1503509384439926844|1503509381939986463|1503509380056748193|1503509377535971329|1503509375493345451|1503509373161439286|1503509370435276950', 'en', 1),
('txtSectionBreakLine', '═══════════════', 'en', 1);