-- Context: config_turn
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('txtDelayStoryStart', 'Delay Story Start? (leave blank to start immediately):', 'en', 1),
('txtAndOr', 'and/or', 'en', 1),
('txtStoryCreatorAdd', 'You''ll be added as the first writer in the story. Please provide:', 'en', 1),
('txtMustBeNo', '[Field label text] must be a number.', 'en', 1),
('txtStoryThreadTitle', 'Story ID: [story_id] - [inputStoryTitle] - [story_status]', 'en', 1),
('txtTurnThreadTitle', 'Turn [storyTurnNumber] - Story ID: [story_id] - [user display name]', 'en', 1),
('txtDMTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.\n-# Use `/mystory help` to see your writer commands.', 'en', 1),
('txtMentionTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.\n-# Use `/mystory help` to see your writer commands.', 'en', 1),
('txtDMTurnReminder', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Your deadline is [turn_end_full] ([turn_end_relative]). Don''t forget to write your entry.', 'en', 1),
('txtMentionTurnReminder', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Your deadline is [turn_end_full] ([turn_end_relative]). Don''t forget to write your entry.', 'en', 1),
('btnFinalizeEntry', '✅ Finalize Entry', 'en', 1),
('btnSkipTurn', '⏭️ Skip Turn', 'en', 1),
('btnViewLastEntry', '📖 View Last Entry', 'en', 1),
('txtStoryActive', 'Your story is now active!', 'en', 1),
('txtThreadCreationFailed', 'Failed to create story thread. Please contact the administrator.', 'en', 1),
('txtDMFailed', 'Could not send direct message. Check your privacy settings.', 'en', 1),
('lblWriteEntry', 'Your Story Entry (up to 4000 characters)', 'en', 1),
('txtWriteWarning', 'TEXT IS NOT SAVED UNTIL SUBMITTED!', 'en', 1),
('txtWritePlaceholder', 'Paste your entry here...', 'en', 1),
('txtStoryNotActive', 'This story is not active. You cannot write entries for paused or closed stories.', 'en', 1),
('txtPendingEntryExists', 'You already have a pending entry. This will overwrite it. Continue?', 'en', 1),
('txtStoryNotFound', 'Story not found.', 'en', 1),
('txtStoryWrongGuild', 'Story not found in this server.', 'en', 1),
('txtWriteFormFailed', 'Failed to open write form. Please try again.', 'en', 1),
('txtEntryProcessFailed', 'Failed to process entry. Please try again.', 'en', 1),
('txtPreviewTitle', '📖 Entry Preview', 'en', 1),
('txtPreviewDescription', '**Review your entry before final submission:**', 'en', 1),
('txtPreviewExpires', '⏰ Expires', 'en', 1),
('lblYourEntry', '✍️ Your Entry:', 'en', 1),
('lblEntryContinued', '✍️ Continued ([count]):', 'en', 1),
('lblEntryStats', '📊 Entry Stats:', 'en', 1),
('txtEntryStatsTemplate', 'Characters: [char_count]/4000
Words: ~[word_count]', 'en', 1),
('txtEntrySubmitted', '✅ **Entry submitted successfully!** The turn will advance to the next writer.', 'en', 1),
('txtEntryDiscarded', '🗑️ **Entry discarded.** You can write a new entry by using the /story write command again.', 'en', 1),
('txtDMReminder', '📝 **Pending Entry Reminder** - You have an entry waiting for confirmation.', 'en', 1),
('txtRecoveryInstructions', 'If you lost the confirmation message, use `/story myturn pending` to recover it.', 'en', 1),
('txtEmptyEntry','You need to write something in the thread before finalizing your entry.', 'en', 1),
('txtEntryFinalized','✅ Entry finalized successfully! The turn has been completed.', 'en', 1),
('txtSkipSuccess', '✅ Turn skipped. The next writer has been notified.', 'en', 1),
('txtFailedtoFinalize', 'Failed to finalize entry. Please try again.', 'en', 1),
('txtWriterStatusPaused', '⏸ You are paused in this story — use /mystory resume to rejoin the rotation.', 'en', 1),
('txtStoryNotFoundOrClosed', 'Story not found or already closed.', 'en', 1),
('txtTurnThreadResumed', '▶️ **Story resumed.** Your turn deadline has been reset to [turn_end_time]. Use the buttons above to finalize or skip your turn when ready.', 'en', 1),
('txtTurnResumed', '🎭 **[story_title] has resumed and your turn is back on!** Your new deadline is [turn_end_time]. [turn_thread_link]', 'en', 1),
('txtStoryThreadTurnStart', '✍️ **Turn [turn_number]:** It''s **[writer_name]**''s turn! Deadline: [turn_end_full] ([turn_end_relative]).', 'en', 1),
('txtStoryThreadTurnSkip', '⏭️ **[writer_name]** skipped their turn.', 'en', 1),
('txtStoryThreadTurnTimeout', '⏰ **[writer_name]**''s turn timed out and was automatically skipped.', 'en', 1),
('txtStoryThreadWriterJoin', '👋 **[writer_name]** joined the story.', 'en', 1),
('txtStoryThreadWriterRemove', '🚫 **[writer_name]** was removed from the story by an admin.', 'en', 1),
('txtStoryThreadCreatorTip', '-# ⭐ **Story creator:** Use `/story manage [story_id]` to add a summary, tags, and adjust settings at any time.', 'en', 1),
('btnFinalizeConfirm', 'Yes, Finalize Entry', 'en', 1),
('btnSkipConfirm', 'Yes, Skip My Turn', 'en', 1),
('btnSkipCancel', 'Cancel', 'en', 1),
('txtEditEntryNotFound', 'Entry not found or not yet confirmed.', 'en', 1),
('txtEditEntryEmpty', 'Entry content cannot be empty.', 'en', 1),
('txtEditNotAuthorized', 'You don''t have permission to edit this entry.', 'en', 1),
('txtEditSessionExpired', 'Your edit session has expired. Please run /story edit again.', 'en', 1),
('txtEditSuccess', 'Entry updated.', 'en', 1),
('txtEditRestoreSuccess', 'Entry restored.', 'en', 1),
('txtEditHistoryNotFound', 'History version not found.', 'en', 1),
('btnRepostEntry', '📢 Repost to Story Thread', 'en', 1),
('txtRepostSuccess', '✅ Entry reposted to the story thread.', 'en', 1),
('txtRepostThreadNotFound', 'Story thread not found — cannot repost.', 'en', 1),
('btnRequestMoreTime', '⏰ Request More Time', 'en', 1),
('txtRequestMoreTimePost', '**[writer_name]** has requested more time on their turn in **[story_title]**. [admin_role]', 'en', 1),
('txtRequestMoreTimeUsed', '⏰ More time has been requested. An admin will review.', 'en', 1),
('txtRequestMoreTimeAlreadyUsed', 'More time has already been requested for this turn.', 'en', 1),
('txtRequestMoreTimeNotYourTurn', 'This button is only available to the current turn holder.', 'en', 1),
('txtTimeleftNoActiveTurn', 'No active turn found for that story.', 'en', 1),
('txtDMTurnStartQuick', '🎭 **Your turn has started in [story_title]!** [Click here to write your entry.]([turn_thread_link])\n-# Use /mystory help to see your writer commands.', 'en', 1),
('txtMentionTurnStartQuick', '🎭 **Your turn has started in [story_title]!** [Click here to write your entry.]([turn_thread_link])\n-# Use /mystory help to see your writer commands.', 'en', 1),
('txtDMTurnStartNormal', '🎭 **Your turn has started in [story_title]!** You can now write your part of the story in your turn thread: [turn_thread_link]\n-# [Return to the server]([turn_thread_link]) and use `/mystory help` to see the commands available to writers.', 'en', 1),
('txtMentionTurnStartNormal', '🎭 **Your turn has started in [story_title]!** You can now write your part of the story in your turn thread: [turn_thread_link]\n-# Use /mystory help to see the commands available to writers.', 'en', 1),
('txtDMTurnReminderQuick', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). [Click here to write your entry.]([turn_thread_link])', 'en', 1),
('txtMentionTurnReminderQuick', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). [Click here to write your entry.]([turn_thread_link])', 'en', 1),
('txtDMTurnReminderNormal', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). [Return to your turn thread]([turn_thread_link]) to finalize your entry.', 'en', 1),
('txtMentionTurnReminderNormal', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). Return to your turn thread: [turn_thread_link]', 'en', 1),
('txtWriteTurnEnded', 'Your turn has already ended — the story has moved on.', 'en', 1),
('txtWriteAlreadySubmitted', 'Your entry has already been submitted.', 'en', 1),
('txtMediaPostLabel', '📎 Story #[story_id] — Turn [turn_id]', 'en', 1),
('txtPingWriters', '📢 [mentions]\n[message]', 'en', 1),
('txtPingWritersSent', '✅ All active writers have been pinged in the story thread.', 'en', 1),
-- Moved from config_other: turn/finalize/skip/validation keys
('txtStoryFeedTurnStart', '✍️ **[story_title]:** [current_writer]''s turn has started! Turn ends [turn_end_date].', 'en', 1),
('txtTimeoutReminderValidation', 'Timeout Reminder must be a number between 0 and 100.', 'en', 1),
('txtHideTurnThreadsValidation', 'Hide Turn Threads must be "off" or "on".', 'en', 1),
('txtTurnLengthPlaceholder', 'Enter number of hours', 'en', 1),
('txtTimeoutReminderPlaceholder', 'Enter: 0, 25, 50, or 75', 'en', 1),
('txtHideTurnThreadsPlaceholder', 'Enter: off or on', 'en', 1),
('txtFinalizeConfirm', 'Finalize your entry?', 'en', 1),
('txtFinalizeConfirmDesc', 'This will submit everything shown below and advance to the next writer. This cannot be undone.', 'en', 1),
('lblFinalizePreviewEntry', 'Your Entry', 'en', 1),
('txtFinalizeImageReview', 'Images in the entry will display with this text:\n*filename : display text*\n[image_list]\n\nTo change the link text, cancel the finalization and edit the image post.', 'en', 1),
('txtSkipConfirmNoContent', '⏭️ **Skip your turn?** This will pass to the next writer without submitting an entry. This cannot be undone.', 'en', 1),
('txtSkipConfirmHasContent', '⚠️ **Skip your turn?** You have posted content in this thread — **it will be discarded** if you skip. This cannot be undone.', 'en', 1),
('txtReadEntryNotFound', 'Entry not found in session. Please use `/story read` again.', 'en', 1),
('txtReadSessionExpired', 'This reading session has expired. Use `/story read` again.', 'en', 1),
-- Silo 5: status embed strings
('txtStatusLegendCreator', '⭐ Creator', 'en', 1),
('txtStatusLegendCurrentTurn', '✍️ Current turn', 'en', 1),
('txtStatusLegendNextUp', '📌 Next up', 'en', 1),
('txtStatusLegendPaused', '⏸️ Paused', 'en', 1),
('txtStatusNoActiveTurn', 'You do not have an active turn.', 'en', 1),
('txtStatusNextManual', '*(manually set)*', 'en', 1),
('txtStatusNextFixed', '*(next in order)*', 'en', 1),
('txtStatusNextRoundRobin', '*Round Robin selection*', 'en', 1),
('txtStatusNextRandom', '*Random selection*', 'en', 1),
('txtStatusReminderSuffix', ' · reminder at [percent]%', 'en', 1),
('txtStatusNoEntries', 'No entries yet', 'en', 1),
('txtStatusEntryStats', '[entry_count] entries · ~[word_count] words[image_part]', 'en', 1),
-- Silo 5: status embed field labels
('lblStatusTags', 'Tags', 'en', 1),
('lblStatusStatus', 'Status', 'en', 1),
('lblStatusMode', 'Mode', 'en', 1),
('lblStatusWriterOrder', 'Writer Order', 'en', 1),
('lblStatusTurnLength', 'Turn Length', 'en', 1),
('lblStatusWriters', 'Writers', 'en', 1),
('lblStatusShowAuthors', 'Show Authors', 'en', 1),
('lblStatusCurrentTurn', 'Current Turn', 'en', 1),
('lblStatusNextWriter', 'Next Writer', 'en', 1),
('lblStatusEntries', 'Entries', 'en', 1),
('lblStatusWriterList', 'Writer List', 'en', 1),
('lblStatusClosed', 'Closed', 'en', 1);