-- Context: config_metadata
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('txtExportAO3Instructions', 'If you don''t see a download icon, click the ··· menu on the file and choose **Download**.\n\n**To post to AO3:** Open the file in any text editor and copy everything between the `[body]` and `[/body]` tags. In AO3''s Work Text field, click the **HTML** button to switch to HTML mode, then paste. If your story includes images, you''ll need to host them on an image host and update the links in the file before copying.', 'en', 1),
('btnExportPostPublicly', '📢 Post to Story Thread', 'en', 1),
('txtExportPostedPublicly', '✅ Story file posted to the story thread.', 'en', 1),
('lblRating', 'Rating', 'en', 1),
('lblWarnings', 'Content Warnings', 'en', 1),
('lblMainPairing', 'Main Pairing', 'en', 1),
('lblOtherRelationships', 'Other Relationships', 'en', 1),
('lblCharacters', 'Characters', 'en', 1),
('lblDynamic', 'Dynamic', 'en', 1),
('lblAdditionalTags', 'Additional Tags', 'en', 1),
('btnSetMetadata', 'Open Metadata Panel', 'en', 1),
('txtRatingBadgeNR', '[NR]', 'en', 1),
('txtRatingBadgeG', '[G]', 'en', 1),
('txtRatingBadgeT', '[T]', 'en', 1),
('txtRatingBadgeM', '[M]', 'en', 1),
('txtRatingBadgeE', '[E]', 'en', 1),
('txtRatingNR', '[NR] Not Rated', 'en', 1),
('txtRatingG', '[G] General', 'en', 1),
('txtRatingT', '[T] Teen', 'en', 1),
('txtRatingM', '[M] Mature', 'en', 1),
('txtRatingE', '[E] Explicit', 'en', 1),
('optWarnAllClear', 'All Clear: No Content Warnings', 'en', 1),
('optWarnViolence', 'Extreme or Visceral Violence', 'en', 1),
('optWarnCharacterDeath', 'Main Character Fatality', 'en', 1),
('optWarnOther', 'Other: See Tags', 'en', 1),
('optWarnNonCon', 'Rape/Lack of Sexual Consent', 'en', 1),
('optWarnMinors', 'Sex Involving a Minor', 'en', 1),
('optWarnUnspecified', 'Unspecified: Warnings May Apply', 'en', 1),
('optDynamicGeneral', 'General', 'en', 1),
('optDynamicFF', 'F/F', 'en', 1),
('optDynamicFM', 'F/M', 'en', 1),
('optDynamicMM', 'M/M', 'en', 1),
('optDynamicPoly', 'Polyamory', 'en', 1),
('optDynamicOther', 'Other', 'en', 1),
('lblRatingChangeThreadWarning', '⚠️ Rating Changed from [old_rating] to [new_rating]', 'en', 1),
('txtMetaApplied', '✅ Changes staged. Click **Save Settings** to apply.', 'en', 1),
('txtRatingChangeThreadWarning', '⚠️ **Rating Change:** Your selection moves the story to a different level of age-restriction. Future story activity will be moved.', 'en', 1),
('txtRatingChangeConfirmTitle', '⚠️ Rating Change — Story Thread Migration Required', 'en', 1),
('txtRatingChangeConfirmBody', 'Changing the rating from **[old_rating]** to **[new_rating]** moves the story''s rating to a different level of age-restriction. All future story activity will be moved to a new thread, and the old thread will be archived and locked. If you''ve already made this change once before, it will move the story back to the original thread.\n\nThis change will **NOT** take effect until you click **Save Settings**. You can cancel or revert this change before saving.', 'en', 1),
('btnRatingChangeConfirm', '✅ Stage Rating Change', 'en', 1),
('btnRatingChangeRevert', '↩️ Keep Current Rating', 'en', 1),
('txtStoryThreadMigratedOut', 'You can find the story continued here: [new_thread_link]', 'en', 1),
('txtStoryThreadMigratedIn', 'This story continues from a previous thread. You can find the earlier entries here: [old_thread_link]', 'en', 1);
('txtRestrictedStoryNotHere', '🔞 This story is rated **[rating]** and can only be read in the age-restricted story channel.', 'en', 1),
('txtTagSubmitModalTitle', 'Suggest a Tag', 'en', 1),
('txtTagSubmitPlaceholder', 'Enter a single tag (e.g. slow burn, hurt/comfort, AU)', 'en', 1),
('txtTagSubmitSuccess', '✅ Your tag suggestion has been submitted to the story creator for review.', 'en', 1),
('txtTagSubmitNotWriter', '❌ Only active writers in this story can submit tag suggestions.', 'en', 1),
('txtTagSubmitDuplicate', '❌ That tag has already been suggested and is pending review.', 'en', 1),
('txtTagPendingTitle', '🏷️ Pending Tag Suggestions — [story_title]', 'en', 1),
('txtTagNoPending', 'There are no pending tag suggestions for this story.', 'en', 1),
('btnTagApprove', '✅ Approve', 'en', 1),
('btnTagReject', '❌ Reject', 'en', 1),
('txtTagApproved', '✅ Tag **[tag_text]** approved and added to the story.', 'en', 1),
('txtTagRejected', '❌ Tag **[tag_text]** rejected.', 'en', 1),
('txtTagStatus', '-# [emoji_status] by [reviewed_by] on [reviewed_at]', 'en', 1),
('txtTagNotCreator', '❌ Only the story creator can review tag suggestions.', 'en', 1),
('txtTagReviewSessionExpired', 'This tag review session has expired. Use /story manage to open tag review again.', 'en', 1),
('btnReviewTags', '🏷️ Review Tags ([count])', 'en', 1),
('txtSelectionStaged', 'Selection saved — click **Save Settings** on the panel to apply.', 'en', 1),
('btnViewTags', '🏷️ View Tags', 'en', 1),
('btnEditTags', '✏️ Edit Tags', 'en', 1),
('txtTagSubmitModalTitleRead', 'Submit a Tag', 'en', 1),
('txtTagVoteCount', '👍 [up] · 👎 [down]', 'en', 1),
('txtTagVoteNote', '-# Vote in the story thread, or use Approve/Reject below.', 'en', 1),
('txtTagSubmitPosted', '🏷️ **Tag proposed by [submitter_name]:** [tag_text]\nReact 👍 or 👎 to vote.', 'en', 1),
('txtTagSubmitNoThread', '✅ Tag submitted for review. (No story thread found — reaction voting unavailable.)', 'en', 1),
('txtTagViewNone', 'No pending tag submissions for this story.', 'en', 1),
('lblMetaDynamic', '📊 Dynamic', 'en', 1),
('lblMetaRating', '🛡️ Rating', 'en', 1),
('lblMetaWarnings', '⚠️ Warnings', 'en', 1),
('lblMetaMainRelationship', '💞 Main Relationship', 'en', 1),
('lblMetaOtherRelationships', '🫂 Other Relationships', 'en', 1),
('lblMetaCharacters', '🧑 Characters', 'en', 1),
('lblMetaTags', '🏷️ Tags', 'en', 1),
('lblMetaSummary', '📝 Summary', 'en', 1),
('txtMetaMainRelationshipPlaceholder', 'ex. Bilbo Baggins/Thorin Oakenshield', 'en', 1),
('txtMetaPanelTitle', '🗂️ Story Metadata', 'en', 1),
('txtMetaSaveSuccess', '✅ Metadata saved.', 'en', 1),
-- Moved from config_other: tag submission key
('lblTagSubmitText', 'Tag to suggest', 'en', 1),
-- Tag delete flow
('txtTagDeleteConfirmTitle', 'Delete Tag Suggestion', 'en', 1),
('txtTagDeleteConfirmBody', 'Are you sure you want to delete your suggestion: **"[tag_text]"**? This cannot be undone.', 'en', 1),
('btnTagDeleteConfirm', 'Yes, Delete It', 'en', 1),
('txtTagDeleteSuccess', '"[tag_text]" has been removed. To submit a new tag, click the button on the [story info post]([thread_link]), or type `/story tag story_id:[story_id]`.', 'en', 1),
('txtTagNotSubmitter', '❌ Only the submitter, story creator, or a server admin can delete this tag suggestion.', 'en', 1),
('txtTagDeleteNotFound', '❌ That tag suggestion was not found, or it has already been reviewed or removed.', 'en', 1),
-- Tag panel buttons (thread post + read view)
('btnManageTags', 'Manage Tags', 'en', 1),
('btnViewProposedTags', 'View Proposed Tags', 'en', 1),
-- View Proposed Tags embed
('txtTagPendingTitlePublic', '🏷️ Proposed Tags for [story_title]', 'en', 1),
('txtTagNoPendingPublic', 'There are no pending tag suggestions for this story right now.', 'en', 1),
('lblTagViewNameTag', 'Tag', 'en', 1),
('lblTagViewNameVotes', 'Votes', 'en', 1),
('txtManageWarningSelectInstructions', 'Dismiss menu to apply warnings', 'en', 1);