-- Context: config_storyadmin
INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES
('txtStoryCloseConfirm', 'Are you sure you want to close **[story_title]**?', 'en', 1),
('btnCloseConfirm', '🔒 Close Story', 'en', 1),
('txtStoryClosedPublic', '📕 **[story_title]** is now complete! Thank you to all [writer_count] writer(s) who participated — [turn_count] turns and ~[word_count] words.', 'en', 1),
('txtStoryFeedClosed', '🎉 **Congratulations to the writers of [story_title]!** The story has concluded with [turn_count] turns and ~[word_count] words. Thank you to all [writer_count] writer(s)!', 'en', 1),
('txtSetupPanelTitle', 'Round Robin StoryBot Setup', 'en', 1),
('txtSetupRequiredAdmin', '⚠️ **Round Robin StoryBot has not been configured for this server.** Please run `/storyadmin setup` to set the story feed channel and admin role before using any other commands.', 'en', 1),
('txtSetupRequiredUser', '⚠️ **Round Robin StoryBot has not been configured for this server yet.** Please ask a server admin to run `/storyadmin setup`.', 'en', 1),
('txtSetupNoPermission', '❌ You need the Manage Server permission to configure Round Robin StoryBot.', 'en', 1),
('txtSetupFeedChannelInvalid', '❌ Could not find a feed channel with that ID. Please check and try again.', 'en', 1),
('txtSetupMediaChannelInvalid', '❌ Could not find a media channel with that ID. Please check and try again.', 'en', 1),
('txtSetupBotPermsFix', '_## To fix: Edit Channel Permissions to enable the permissions listed above for the [bot_role_name] member profile, not just the role._', 'en', 1),
('btnSetupChannels', 'Configure Feed Channels', 'en', 1),
('btnSetupRoundup', 'Configure Weekly Roundup', 'en', 1),
('btnSetupRole', 'Set Admin Role', 'en', 1),
('btnSetupSave', 'Save Settings', 'en', 1),
('txtSetupModalTitleChannels', 'Configure Feed Channels', 'en', 1),
('txtSetupModalTitleRoundup', 'Configure Weekly Roundup', 'en', 1),
('txtSetupChannelsModalDesc', 'Select the channels for story activity. Only Story Feed channel is required. If Media is blank, images will not be attached to stories. Restricted channels filter mature or explicit rated stories, otherwise they appear in the same channel as all others. Media channels should be set to Private.', 'en', 1),
('txtSetupRoundupModalDesc', 'Configure the weekly roundup digest. Select a roundup channel to enable it or leave unset to disable. Day and hour use UTC time.', 'en', 1),
('txtSetupEmbedDescFeed', '-# This is where all story threads and activity will be posted.', 'en', 1),
('txtSetupEmbedDescMedia', '-# A private channel for story images. If blank, image handling in stories is disabled.', 'en', 1),
('txtSetupEmbedDescAdminRole', '-# Optional. If blank, only Discord server admins can use storyadmin commands.', 'en', 1),
('txtSetupEmbedDescRestrictedFeed', '-# Should be age-restricted if your server is not 18+.', 'en', 1),
('txtSetupEmbedDescRestrictedMedia', '-# Should be private and age-restricted.', 'en', 1),
('txtSetupEmbedDescRoundupChannel', '-# Where the weekly activity summary is posted. Leave blank to disable.', 'en', 1),
('txtSetupEmbedDescRoundupDay', '-# Day of the week to post (0 = Sunday, 6 = Saturday).', 'en', 1),
('txtSetupEmbedDescRoundupHour', '-# Hour to post in UTC (0–23).', 'en', 1),
('txtSetupModalSaveWarning', '## === You Must Click Save Settings to Apply Changes! ===', 'en', 1),
('txtSetupModalTitleFeed', 'Story Feed Channel', 'en', 1),
('txtSetupModalTitleMedia', 'Media/Image Channel', 'en', 1),
('txtSetupModalTitleRole', 'Admin Role', 'en', 1),
('txtSetupModalTitleRestrictedFeed', 'Restricted Feed Channel', 'en', 1),
('txtSetupModalTitleRestrictedMedia', 'Restricted Media Channel', 'en', 1),
('txtSetupModalTitleRoundupChannel', 'Weekly Roundup Channel', 'en', 1),
('txtSetupModalTitleRoundupDay', 'Weekly Roundup Day', 'en', 1),
('txtSetupModalTitleRoundupHour', 'Weekly Roundup Hour', 'en', 1),
('lblSetupModalFieldFeed', 'Story Feed Channel', 'en', 1),
('txtSetupModalPlaceholderFeed', 'Channel #name or ID (required)', 'en', 1),
('lblSetupModalFieldMedia', 'Media/Image Channel', 'en', 1),
('txtSetupModalPlaceholderMedia', 'Channel #name or ID (private, optional)', 'en', 1),
('lblSetupModalFieldRole', 'Admin Role Name', 'en', 1),
('txtSetupModalPlaceholderRole', 'Exact role name, case-sensitive (optional)', 'en', 1),
('lblSetupModalFieldRestrictedFeed', 'Restricted Feed Channel', 'en', 1),
('txtSetupModalPlaceholderRestrictedFeed', 'Channel #name or ID (restricted, optional)', 'en', 1),
('lblSetupModalFieldRestrictedMedia', 'Restricted Media Channel', 'en', 1),
('txtSetupModalPlaceholderRestrictedMedia', 'Channel #name or ID (restricted, optional)', 'en', 1),
('lblSetupModalFieldRoundupChannel', 'Roundup Channel', 'en', 1),
('txtSetupModalPlaceholderRoundupChannel', 'Channel #name or ID. Leave blank to disable.', 'en', 1),
('lblSetupModalFieldRoundupDay', 'Day of Week (0=Sun, 1=Mon … 6=Sat)', 'en', 1),
('txtSetupModalPlaceholderRoundupDay', 'Enter 0–6 (default: 1 = Monday)', 'en', 1),
('lblSetupModalFieldRoundupHour', 'Hour (UTC, 0–23)', 'en', 1),
('txtSetupModalPlaceholderRoundupHour', 'Enter 0–23 (default: 9 = 9:00 AM UTC)', 'en', 1),
('txtAdminOnly', '❌ You need admin permissions to use this command.', 'en', 1),
('txtAdminNoActiveTurn', 'There is no active turn in this story.', 'en', 1),
('txtAdminSkipSuccess', '✅ Turn skipped. The next writer has been notified.', 'en', 1),
('txtAdminExtendSuccess', '✅ Turn extended by [hours] hour(s). New deadline: [new_end_time].', 'en', 1),
('txtAdminKickNotWriter', '❌ [user_name] is not an active writer in this story.', 'en', 1),
('txtAdminKickSuccess', '✅ **[user_name]** has been removed from **[story_title]**.', 'en', 1),
('txtAdminPauseUserSuccess', '✅ **[user_name]** has been paused in **[story_title]**.', 'en', 1),
('txtAdminUnpauseUserSuccess', '✅ **[user_name]** has been returned to active rotation in **[story_title]**.', 'en', 1),
('txtAdminUnpauseNotPaused', '❌ [user_name] is not currently paused in this story.', 'en', 1),
('txtAdminPenNameSuccess', '✅ Pen name for **[user_name]** updated to **[pen_name]**.', 'en', 1),
('txtAdminMUPauseConfirmDesc', '**[user_name]** will be temporarily removed from the turn rotation in **[story_title]**. They can rejoin at any time with /mystory resume.', 'en', 1),
('txtAdminMUUnpauseConfirmDesc', '**[user_name]** will be returned to active rotation in **[story_title]** and will be selected the next time the cycle reaches them.', 'en', 1),
('txtAdminMURemoveConfirmDesc', '**[user_name]** will be permanently removed from **[story_title]**. This cannot be undone.', 'en', 1),
('txtAdminMUActiveTurnWarning', '⚠️ It is currently **[user_name]**''s turn. Confirming will auto-pass to the next writer.', 'en', 1),
('txtAdminMULastWriterWarning', '🔴 **[user_name]** is the last active writer. Removing them will automatically close the story.', 'en', 1),
('txtManageUserPanelTitle', 'Managing **[writer_name]** in **[story_title]**', 'en', 1),
('lblManageUserStatus', 'Status', 'en', 1),
('lblManageUserPenName', 'Pen Name', 'en', 1),
('lblManageUserNotif', 'Notifications', 'en', 1),
('lblManageUserPrivacy', 'Turn Privacy', 'en', 1),
('btnManageUserClose', 'Close', 'en', 1),
('txtAdminPauseSuccess', '⏸️ **[story_title]** has been paused.', 'en', 1),
('txtAdminAlreadyPaused', 'This story is already paused.', 'en', 1),
('txtAdminAlreadyActive', 'This story is already active.', 'en', 1),
('txtAdminResumeSuccess', '▶️ **[story_title]** has been resumed.', 'en', 1),
('txtAdminDeleteConfirm', '⚠️ Are you sure you want to **permanently delete** "[story_title]"? All turns, entries, and writer data will be gone. This cannot be undone.', 'en', 1),
('txtAdminDeleteSuccess', '✅ **[story_title]** has been permanently deleted.', 'en', 1),
('txtAdminDeleteEntryAlreadyDeleted', 'This entry has already been deleted.', 'en', 1),
('txtAdminDeleteEntrySuccess', 'Entry by **[author_name]** has been deleted. Entry ID: `[entry_id]` — to restore, use `/storyadmin restoreentry entry_id:[entry_id]`.', 'en', 1),
('txtAdminRestoreEntryNotDeleted', 'That entry is not deleted — nothing to restore.', 'en', 1),
('txtAdminRestoreEntrySuccess', 'Entry by **[author_name]** has been restored and will appear in `/story read` and exports again.', 'en', 1),
('txtAdminConfigTitle', '⚙️ Story Settings — [story_title]', 'en', 1),
('txtAdminConfigSaved', '✅ Story settings saved.', 'en', 1),
('btnAdminConfigSave', '✅ Save Changes', 'en', 1),
('lblAllowLateJoins', 'Allow Late Joins', 'en', 1),
('lblOpenToWriters', 'Allow Joins', 'en', 1),
('lblSummary', 'Story Summary', 'en', 1),
('btnSetSummary', 'Set Summary', 'en', 1),
('lblTags', 'Tags', 'en', 1),
('btnSetTags', 'Set Tags', 'en', 1),
('txtManageNotAuthorized', '❌ Only the story creator or an admin can manage this story.', 'en', 1),
('txtManageValidationTurnLength', 'Turn length must be at least 1 hour.', 'en', 1),
('txtManageValidationTimeout', 'Timeout reminder must be a number between 0 and 100.', 'en', 1),
('txtManageValidationMaxWriters', 'Max writers must be at least 1, or leave blank for no limit.', 'en', 1),
('txtAdminNextSuccess', '✅ **[user_name]** will receive the next turn.', 'en', 1),
('txtAdminNextAlreadyCurrent', '❌ **[user_name]** is already the current writer.', 'en', 1),
('txtAdminReassignSuccess', '✅ Turn reassigned to **[prev_writer]**. **[current_writer]** will go next.', 'en', 1),
('txtAdminReassignNoPreviousWriter', '❌ There is no previous turn to reassign from — this is the first turn in the story.', 'en', 1),
('cfgWeeklyRoundupEnabled', '0', 'en', 1),
('cfgWeeklyRoundupDay', '1', 'en', 1),
('cfgWeeklyRoundupHour', '9', 'en', 1),
('cfgWeeklyRoundupChannelId', '', 'en', 1),
('cfgWeeklyRoundupColor', '#57F287', 'en', 1),
('txtRoundupDay0', 'Sunday', 'en', 1),
('txtRoundupDay1', 'Monday', 'en', 1),
('txtRoundupDay2', 'Tuesday', 'en', 1),
('txtRoundupDay3', 'Wednesday', 'en', 1),
('txtRoundupDay4', 'Thursday', 'en', 1),
('txtRoundupDay5', 'Friday', 'en', 1),
('txtRoundupDay6', 'Saturday', 'en', 1),
('txtWeeklyRoundupTitle', '📖 Weekly Story Roundup', 'en', 1),
('txtRoundupNoActiveStories', '*No active stories this week.*', 'en', 1),
('txtRoundupStoryLine', '• **[story_title]** (#[story_id])', 'en', 1),
('txtRoundupActivity', 'Stories created: **[created]** · Stories completed: **[completed]**\nTurns submitted: **[submitted]** · Turns missed: **[missed]**\nWords written: **~[word_count]**', 'en', 1),
('txtRoundupOverflow', '*...and [count] more*', 'en', 1),
('lblRoundupActiveStories', '📚 Active Stories', 'en', 1),
('lblRoundupActivity', '📊 This Week''s Activity', 'en', 1),
('lblRoundupWriters', '👥 Active Writers', 'en', 1),
('txtAdminMUSaved', '✅ Writer settings saved for **[writer_name]** in **[story_title]**.', 'en', 1),
('btnTurnSkip', '⏭️ Skip Current Turn', 'en', 1),
('btnTurnExtend', '⏰ Extend Deadline', 'en', 1),
('btnTurnNext', '👆 Designate Next Writer', 'en', 1),
('btnTurnReassign', '↩️ Reassign to Previous', 'en', 1),
('btnTurnDeleteEntry', '🗑️ Delete an Entry', 'en', 1),
('btnTurnRestoreEntry', '♻️ Restore Deleted Entry', 'en', 1),
('txtTurnActionsNoTurn', 'No active turn.', 'en', 1),
('txtManageEmbedTitle', 'Story Settings', 'en', 1),
('lblManageStoryTitle', '📖 Story Title', 'en', 1),
('lblManageStoryStatus', 'Story Status', 'en', 1),
('lblManageJoinStatus', 'Join Status', 'en', 1),
('txtManageSectionBreakMeta', '**📋 Story Metadata**', 'en', 1),
('txtManageSetTitleModalTitle', 'Edit Story Title', 'en', 1),
('txtManageSetTitlePlaceholder', 'Enter the new story title', 'en', 1),
('btnManageTurns', 'Manage Turns', 'en', 1),
('btnManageEntries', 'Manage Entries', 'en', 1),
('txtManageTurnsPanelTitle', 'Turn Actions — [story_title]', 'en', 1),
('txtManageTurnsNoTurn', 'No active turn.', 'en', 1),
('txtManageTurnsActiveTurn', 'Active writer: **[writer_name]** · Turn ends <t:[turn_ends_unix]:R>', 'en', 1),
('txtManageEntriesSelectWriter', 'Select a writer to browse their entries:', 'en', 1),
('txtManageEntriesFilterModal', 'Filter Writers by Name', 'en', 1),
('txtManageEntriesFilterPlaceholder', 'e.g. shanti', 'en', 1),
('txtManageEntriesNoWriters', '❌ No writers with entries found for this story.', 'en', 1),
('txtManageEntriesNoMatch', '❌ No writers matched that filter. Try a different name fragment.', 'en', 1),
('txtManageEntriesSelectEntry', 'Select an entry to preview:', 'en', 1),
('txtManageEntriesNoEntries', '❌ No entries found for this writer.', 'en', 1),
('txtManageEntriesPreviewTitle', 'Turn [turn_number] — [writer_name]', 'en', 1),
('txtManageEntriesPreviewFooter', 'Entry ID: [entry_id] · Status: [status] · ~[word_count] words', 'en', 1),
('btnManageEntriesDelete', 'Delete Entry', 'en', 1),
('btnManageEntriesRestore', 'Restore Entry', 'en', 1),
('btnManageEntriesBack', 'Back', 'en', 1),
('txtStoryCloseNotAuthorized', 'You do not have permission to close this story. Only the story creator or an admin can close a story.', 'en', 1),
('txtSetupRoundupDayInvalid', '❌ Day must be a number between 0 (Sunday) and 6 (Saturday).', 'en', 1),
('txtSetupRoundupHourInvalid', '❌ Hour must be a number between 0 and 23 (UTC).', 'en', 1),
('btnAdminMUPause', '⏸️ Pause', 'en', 1),
('btnAdminMUUnpause', '▶️ Restore', 'en', 1),
('btnAdminMURemove', 'Remove', 'en', 1),
('btnAdminMUPenName', 'Update Name', 'en', 1),
('btnConfirmDelete', '🗑️ Permanently Delete', 'en', 1),
('btnAdminMUSave', '✅ Save Settings', 'en', 1),
('lblAdminMUNotif', 'Notifications', 'en', 1),
('lblAdminMUPrivacy', 'Turn Privacy', 'en', 1),
('btnAdminMUToggleNotif', 'Toggle Notifications', 'en', 1),
('btnAdminMUTogglePrivacy', 'Toggle Turn Privacy', 'en', 1),
('txtTurnSkipConfirm', '⏭️ **Skip [writer_name]''s turn in [story_title]?** This will end their turn immediately and advance to the next writer.', 'en', 1),
('txtTurnExtendModalTitle', 'Extend Deadline', 'en', 1),
('lblTurnExtendHours', 'Hours to add', 'en', 1),
('txtTurnExtendPlaceholder', 'Enter number of hours (e.g. 24)', 'en', 1),
('txtTurnNextModalTitle', 'Designate Next Writer', 'en', 1),
('lblTurnNextUser', 'Discord User ID or mention', 'en', 1),
('txtTurnNextPlaceholder', 'Enter @mention or user ID', 'en', 1),
('txtTurnReassignConfirm', '↩️ **Reassign turn to [prev_writer]?** They will get a new turn immediately, then [current_writer] will go next.', 'en', 1),
('txtTurnDeleteEntryModalTitle', 'Delete Entry by Turn Number', 'en', 1),
('lblTurnDeleteEntryTurn', 'Turn number (as shown in /story read)', 'en', 1),
('txtTurnDeleteEntryPlaceholder', 'Enter turn number', 'en', 1),
('txtTurnRestoreEntryModalTitle', 'Restore Deleted Entry', 'en', 1),
('lblTurnRestoreEntryId', 'Entry ID', 'en', 1),
('txtTurnRestoreEntryPlaceholder', 'Enter entry ID (shown when entry was deleted)', 'en', 1),
('txtTurnNextSelectWrite', 'Select the writer who will receive the next turn:', 'en', 1),
('cfgRestrictedFeedChannelId', '', 'en', 1),
('cfgRestrictedMediaChannelId', '', 'en', 1),
('txtSetupRestrictedChannelInvalid', '❌ Could not find the restricted feed channel with that ID. Please check and try again.', 'en', 1),
('txtSetupRestrictedMediaInvalid', '❌ Could not find the restricted media channel with that ID. Please check and try again.', 'en', 1),
('txtManageEntryDeleteSuccess', '✅ Entry deleted. Entry ID: **[entry_id]** (use Restore Entry to undo).', 'en', 1),
('txtManageEntryRestoreSuccess', '✅ Entry restored for **[writer_name]**.', 'en', 1),
('txtManageEntryAlreadyDeleted', '❌ This entry is already deleted.', 'en', 1),
('txtManageEntryAlreadyConfirmed', '❌ This entry is not deleted.', 'en', 1),
-- Added Silo 3: manageUser.js
('txtManageUserPanelDesc', '-# Changes are staged — click **Save Settings** to apply notifications/privacy. Status actions (Pause/Restore/Remove) apply immediately.', 'en', 1),
('txtNotifDM', 'DM', 'en', 1),
('txtNotifMention', 'Mention in channel', 'en', 1),
('btnManageUserSwitchMention', 'Switch to: Mention', 'en', 1),
('btnManageUserSwitchDM', 'Switch to: DM', 'en', 1),
('btnManageUserMakePublic', 'Make Public', 'en', 1),
('btnManageUserMakePrivate', 'Make Private', 'en', 1),
('txtAdminMUPauseConfirmTitle', '⏸️ Pause Writer?', 'en', 1),
('txtAdminMUUnpauseConfirmTitle', '▶️ Restore to Rotation?', 'en', 1),
('txtAdminMURemoveConfirmTitle', '⚠️ Remove Writer?', 'en', 1),
('txtAdminRemoveAutoClose', '⚠️ Story auto-closed — no writers remain.', 'en', 1),
('txtAdminMUPenNamePlaceholder', 'Leave blank to clear', 'en', 1),
-- Added Silo 3: manageTurnActions.js
('txtTurnExtendInvalidHours', '❌ Hours must be a positive number.', 'en', 1),
('txtTurnDeleteEntryInvalidNumber', '❌ Turn number must be a positive integer.', 'en', 1),
('txtTurnRestoreEntryInvalidId', '❌ Entry ID must be a positive integer.', 'en', 1),
('txtTurnNextSelectPlaceholder', 'Select the next writer...', 'en', 1),
('txtTurnDeleteEntryConfirmTitle', 'Delete Turn [turn_number] — [writer_name]?', 'en', 1),
('txtTurnDeleteEntryConfirmNote', 'This entry will be hidden from `/story read` and exports. The entry ID shown after deletion can be used to restore it.', 'en', 1),
('btnTurnDeleteEntryConfirm', 'Delete Entry', 'en', 1),
-- Added Silo 3: manageEntries.js
('txtManageEntriesMoreWriters', 'More writers ([offset]+)...', 'en', 1),
('txtManageEntriesWriterPlaceholder', 'Select a writer...', 'en', 1),
('txtManageEntriesMoreEntries', 'More entries ([offset]+)...', 'en', 1),
('txtManageEntriesEntryPlaceholder', 'Select an entry...', 'en', 1),
('txtManageEntriesDeletedFlag', '[DELETED]', 'en', 1),
('txtManageEntriesContinued', '*...entry continues*', 'en', 1),
-- Added Silo 3: storyadmin.js setup
('txtSetupAgeRestrictNote', '*(Age-restrict this channel if the server is not already 18+)*', 'en', 1),
('txtSetupNoMediaNote', 'ℹ️ No media channel set — images will not be processed.', 'en', 1),
('txtSetupNoRoleNote', 'ℹ️ No admin role set — only Discord Administrators can use admin commands.', 'en', 1),
('txtSetupRoundupDisabledNote', 'ℹ️ Weekly roundup disabled.', 'en', 1),
('txtSetupSupportInvite', 'Need help? Join our support server: https://discord.gg/hKH9G5XFpJ', 'en', 1),
('lblSetupChangelog', 'Hub Announcements', 'en', 1),
('txtSetupEmbedDescChangelog', 'Receive changelogs and announcements from the Round Robin StoryBot Hub in your story feed channel.', 'en', 1),
('txtHubAnnouncementTitle', '📢 Round Robin StoryBot Announcement', 'en', 1),
('txtHubAnnouncementFooter', 'Join the Round Robin StoryBot Hub Server for more information.', 'en', 1),
-- Reopen story
('txtReopenStory', 'Reopen Story', 'en', 1),
('txtReopenSuccess', '✅ **[story_title]** has been reopened. A new turn has started and the story is [join_status] to new writers.', 'en', 1);