-- Sample config entries for testing the story system
-- Insert default English config values for system (guild_id = 1)

INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES

-- Field Labels
('lblStoryTitle', 'Story Title:', 'en', 1),
('lblQuickMode', 'Quick Mode?:', 'en', 1),
('lblTurnLength', 'Turn Length (hours):', 'en', 1),
('lblTimeoutReminder', 'Timeout Reminder Interval:', 'en', 1),
('lblHideTurnThreads', 'Hide Turn Threads?', 'en', 1),
('lblNoHours', 'By # of Hours (if applicable):', 'en', 1),
('lblNoWriters', '# of Writers (if applicable):', 'en', 1),
('lblMaxWriters', 'Max Writers (optional):', 'en', 1),
('btnSetMaxWriters', 'Set Max Writers', 'en', 1),
('lblYourAO3Name', 'Your AO3 Username:', 'en', 1),
('lblKeepYourPrivate', 'Keep your turn threads private?:', 'en', 1),

-- Text Messages
('txtDelayStoryStart', 'Delay Story Start? (leave blank to start immediately):', 'en', 1),
('txtAndOr', 'and/or', 'en', 1),
('txtStoryCreatorAdd', 'You''ll be added as the first writer in the story. Please provide:', 'en', 1),
('txtMustBeNo', '[Field label text] must be a number.', 'en', 1),
('txtStoryThreadTitle', 'Story ID: [story_id] - [inputStoryTitle] - [story_status]', 'en', 1),
('txtTurnThreadTitle', 'Story ID: [story_id] - Turn [storyTurnNumber] - [user display name] - Ends [turnEndTime]', 'en', 1),
('txtDMTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.', 'en', 1),
('txtMentionTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.', 'en', 1),
('txtDMTurnReminder', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Don''t forget to write your entry.', 'en', 1),
('txtMentionTurnReminder', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Don''t forget to write your entry.', 'en', 1),
('txtNormalModeWelcome', '## Welcome to your turn thread for *[story_title]*\nWrite your story entry here in as many posts as you''d like. Edit as needed, use Discord markdown for formatting, and upload images as separate posts in between your text so they''ll appear in that order in the story. Then, use the buttons below to Finalize your turn, or Skip to pass to the next writer without submitting.\n\nYour turn ends on [turn_end_full], in [turn_end_relative].\n-# If you need to catch up with the story since your last turn, use the command `/mystory catchup story_id:[story_id]`.', 'en', 1),
('txtQuickModeTurnStart', '🎭 **[story_title]:** [current_writer]''s turn has started! Please use `/story write [story_id]` to submit your entry. Turn ends [turn_end_date].', 'en', 1),
('btnFinalizeEntry', '✅ Finalize Entry', 'en', 1),
('btnSkipTurn', '⏭️ Skip Turn', 'en', 1),
('txtAlreadyJoined', 'You have already joined this story!', 'en', 1),
('txtStoryJoinFail', 'You were not added to the story. Please contact an administrator.', 'en', 1),
('txtStoryActive', 'Your story is now active!', 'en', 1),
('txtMoreWritersDelay', 'This story will begin when X more writer(s) join!', 'en', 1),
('txtHoursDelay', 'This story will begin in X hours!', 'en', 1),

-- Story Status Text
('txtClosed', 'Closed', 'en', 1),
('txtActive', 'Active', 'en', 1), 
('txtPaused', 'Paused', 'en', 1),

-- Error Messages
('txtThreadCreationFailed', 'Failed to create story thread. Please contact the administrator.', 'en', 1),
('txtStoryCreated', 'Story created successfully!', 'en', 1),
('txtDMFailed', 'Could not send direct message. Check your privacy settings.', 'en', 1),

-- Write Command Text
('lblWriteEntry', 'Your Story Entry (up to 4000 characters)', 'en', 1),
('txtWriteWarning', 'TEXT IS NOT SAVED UNTIL CONFIRMED!', 'en', 1),
('txtWritePlaceholder', 'Paste your entry here...', 'en', 1),
('txtStoryNotActive', 'This story is not active. You cannot write entries for paused or closed stories.', 'en', 1),
('txtNormalModeWrite', 'This story is in normal mode. Please write your entry in your private turn thread.', 'en', 1),
('txtNotYourTurn', 'It is not your turn to write. Please wait for your turn.', 'en', 1),
('txtPendingEntryExists', 'You already have a pending entry. This will overwrite it. Continue?', 'en', 1),
('txtStoryNotFound', 'Story not found.', 'en', 1),
('txtStoryWrongGuild', 'Story not found in this server.', 'en', 1),
('txtWriteFormFailed', 'Failed to open write form. Please try again.', 'en', 1),
('txtEntryProcessFailed', 'Failed to process entry. Please try again.', 'en', 1),
('txtPreviewTitle', '📖 Entry Preview', 'en', 1),
('txtPreviewDescription', '**Review your entry before final submission:**', 'en', 1),
('txtPreviewExpires', '⏰ Expires', 'en', 1),
('lblYourEntry', '✍️ Your Entry:', 'en', 1),
('lblEntryContinued', '✍️ Continued ([count]):', 'en', 1),
('lblEntryStats', '📊 Entry Stats:', 'en', 1),
('txtEntryStatsTemplate', 'Characters: [char_count]/4000
Words: ~[word_count]', 'en', 1),
('btnSubmit', 'Submit', 'en', 1),
('btnDiscard', 'Discard', 'en', 1),
('txtEntrySubmitted', '✅ **Entry submitted successfully!** The turn will advance to the next writer.', 'en', 1),
('txtEntryDiscarded', '🗑️ **Entry discarded.** You can write a new entry by using the /story write command again.', 'en', 1),
('txtActionFailed', 'Failed to process action. Please try again.', 'en', 1),
('txtDMReminder', '📝 **Pending Entry Reminder** - You have an entry waiting for confirmation.', 'en', 1),
('txtRecoveryInstructions', 'If you lost the confirmation message, use `/story myturn pending` to recover it.', 'en', 1),
('txtEmptyEntry','You need to write something in the thread before finalizing your entry.', 'en', 1),
('txtNoActiveTurn','You do not have an active turn in this story.', 'en', 1),
('txtEntryFinalized','✅ Entry finalized successfully! The turn has been completed.', 'en', 1),
('txtFailedtoFinalize', 'Failed to finalize entry. Please try again.', 'en', 1),

-- Shared UI
('btnCancel', 'Cancel', 'en', 1),
('txtActionCancelled', 'Cancelled.', 'en', 1),
('txtNotActiveWriter', 'You are not an active writer in this story.', 'en', 1),
('txtNoConfirmedEntries', 'This story has no confirmed entries yet.', 'en', 1),

-- MyStory Dashboard
('txtMyStoriesTitle', '📚 Your Active Stories', 'en', 1),
('txtMyStoryNone', '🤷 You''re not currently a writer in any active stories. Use /story join to get started!', 'en', 1),
('txtMyTurnQuick', '🎯 **Your turn!** Use `/story write [story_id]`', 'en', 1),
('txtMyTurnNormal', '🎯 **Your turn!**', 'en', 1),
('txtOthersTurn', '✍️ [writer_name]''s turn', 'en', 1),
('txtMyTurnHistory', '↩️ Last turn [last_turn_at] · [turn_count] turn(s)', 'en', 1),
('txtMyTurnNoHistory', '↩️ No turns yet', 'en', 1),

-- MyStory Catchup
('txtCatchupNoEntries', 'No new entries since your last turn.', 'en', 1),
('txtCatchupSessionExpired', 'Session expired. Please run `/mystory catchup` again.', 'en', 1),

-- MyStory Leave
('txtLeaveConfirm', '⚠️ Are you sure you want to leave **[story_title]**? This cannot be undone.', 'en', 1),
('txtLeaveConfirmMyTurn', '⚠️ It''s currently your turn in **[story_title]**. Leaving will skip your turn. Are you sure?', 'en', 1),
('txtLeaveConfirmLastWriter', '⚠️ You are the **last active writer** in **[story_title]**. Leaving will automatically close the story. Are you sure?', 'en', 1),
('btnLeaveStory', 'Leave Story', 'en', 1),
('txtLeftStorySuccess', '✅ You have left the story.', 'en', 1),

-- MyStory Pass
('txtPassSuccess', '✅ Your turn has been passed.', 'en', 1),

-- Close Story Text
('txtStoryAlreadyClosed', 'This story is already closed.', 'en', 1),
('txtStoryNotFoundOrClosed', 'Story not found or already closed.', 'en', 1),
('txtStoryCloseNotAuthorized', 'You do not have permission to close this story. Only the story creator or an admin can close a story.', 'en', 1),
('txtStoryCloseConfirm', '⚠️ Are you sure you want to close **[story_title]**? The active turn will be ended. This cannot be undone.', 'en', 1),
('btnCloseConfirm', '🔒 Close Story', 'en', 1),
('txtStoryClosedPublic', '📕 **[story_title]** is now complete! Thank you to all [writer_count] writer(s) who participated — [turn_count] turns and ~[word_count] words. The full story is attached below.', 'en', 1),
('txtStoryFeedClosed', '🎉 **Congratulations to the writers of [story_title]!** The story has concluded with [turn_count] turns and ~[word_count] words. Thank you to all [writer_count] writer(s)! The full story is attached below.', 'en', 1),

-- Story List Text
('txtAllStories', 'All Stories', 'en', 1),
('txtJoinableStories', 'Joinable Stories', 'en', 1),
('txtMyStories', 'My Stories', 'en', 1),
('txtActiveStories', 'Active Stories', 'en', 1),
('txtPausedStories', 'Paused Stories', 'en', 1),
('txtNoStoriesFound', '📚 **No stories found** for filter "[filter_name]"', 'en', 1),
('txtStoriesPageTitle', '📚 [filter_title] (Page [page]/[total_pages])', 'en', 1),
('txtStoriesPageDesc', 'Showing [showing] of [total] stories', 'en', 1),
('txtMemberStatusCanJoin', '🟢 Can Join', 'en', 1),
('txtMemberStatusCanNotJoin', '🔴 Cannot Join', 'en', 1),
('txtMemberStatusJoined', '✅ Joined', 'en', 1),
('txtStoryListFailed', 'Failed to load stories. Please try again.', 'en', 1),
('lblStoryStatus', 'Status:', 'en', 1),
('lblStoryTurn', 'Turn:', 'en', 1),
('lblStoryWriters', 'Writers:', 'en', 1),
('lblStoryMode', 'Mode:', 'en', 1),
('lblStoryCreator', 'Creator:', 'en', 1),
('txtModeQuick', 'Quick', 'en', 1),
('txtModeNormal', 'Normal', 'en', 1),
('txtTurnWaiting', 'Waiting to start', 'en', 1),
('txtTurnOverdue', '[writer_name] (overdue)', 'en', 1),
('txtTurnTimeLeft', '[writer_name] ([hours]h left)', 'en', 1),
('txtTurnUnknown', 'Unknown', 'en', 1),

-- Join Command Text  
('lblJoinAO3Name', 'AO3 Username (optional):', 'en', 1),
('lblJoinPrivacy', 'Turn Thread Privacy:', 'en', 1),
('lblJoinNotifications', 'Notification Preference:', 'en', 1),
('txtJoinSuccess', '✅ Successfully joined "[story_title]"! You are writer #[writer_number].', 'en', 1),
('txtJoinStoryFull', '❌ This story has reached its maximum of [max_writers] writers.', 'en', 1),
('txtJoinNotAllowed', '❌ This story does not allow new writers to join after it has started.', 'en', 1),
('txtJoinStoryClosed', '❌ This story is closed and not accepting new writers.', 'en', 1),
('txtStoryFeedJoinAnnouncement', '🎭 **[joiner_name]** just joined **[story_title]**! It\'s currently **[current_writer]**\'s turn until [turn_end_date].', 'en', 1),
('txtStoryFeedCreatedPending', '📚 **New Story Created:** [story_title] by [creator_name]! Waiting for [writers_needed] more writer(s) to start.', 'en', 1),
('txtStoryFeedCreatedDelayed', '📚 **New Story Created:** [story_title] by [creator_name]! Story will start [start_time].', 'en', 1),
('txtStoryFeedCreatedActive', '📚 **New Story Created:** [story_title] by [creator_name]! Story is now active with [writer_count] writer(s).', 'en', 1),
('txtStoryFeedNowActive', '🎬 **[story_title] is now active!** [first_writer] will start the story. Turn ends [turn_end_date].', 'en', 1),
('txtStoryFeedTurnStart', '✍️ **[story_title]:** [current_writer]''s turn has started! Turn ends [turn_end_date].', 'en', 1),
('txtJoinFormFailed', 'Failed to open join form. Please try again.', 'en', 1),
('txtJoinProcessFailed', 'Failed to process join request. Please try again.', 'en', 1),
('txtValidationErrors', '**Validation Errors:**', 'en', 1),
('txtPrivacyValidation', 'Keep Private must be "yes" or "no".', 'en', 1),
('txtQuickModeValidation', 'Quick Mode must be "off" or "on".', 'en', 1),
('txtTimeoutReminderValidation', 'Timeout Reminder must be a number between 0 and 100.', 'en', 1),
('txtHideTurnThreadsValidation', 'Hide Turn Threads must be "off" or "on".', 'en', 1),
('txtFormOpenError', 'Failed to open story creation form. Please try again.', 'en', 1),
('txtFormProcessError', 'Failed to process form. Please try again.', 'en', 1),
('txtAdditionalOptionsError', 'Failed to show additional options form.', 'en', 1),
('txtStoryCreationError', 'Failed to create story. Please try again.', 'en', 1),
('txtNotificationValidation', 'Notification Preference must be "dm" or "mention".', 'en', 1),
('txtJoinPrivacyPlaceholder', 'Enter: public or private', 'en', 1),
('txtJoinNotificationPlaceholder', 'Enter: dm or mention', 'en', 1),
('txtJoinAO3Placeholder', 'Leave blank to use Discord display name', 'en', 1),
('txtQuickModePlaceholder', 'Enter: off or on', 'en', 1),
('txtTurnLengthPlaceholder', 'Enter number of hours', 'en', 1),
('txtTimeoutReminderPlaceholder', 'Enter: 0, 25, 50, or 75', 'en', 1),
('txtHideTurnThreadsPlaceholder', 'Enter: off or on', 'en', 1),
('txtDelayHoursPlaceholder', 'Enter number of hours (optional)', 'en', 1),
('txtDelayWritersPlaceholder', 'Enter number of writers (optional)', 'en', 1),
('txtAO3NamePlaceholder', 'Your AO3 username (optional)', 'en', 1),
('txtKeepPrivatePlaceholder', 'Enter: yes or no', 'en', 1),
('btnPrev', '◀️ Prev', 'en', 1),
('btnNext', 'Next ▶️', 'en', 1),
('btnFilter', '🔍 Filter', 'en', 1),
('txtQuickJoinPlaceholder', 'Quick join a story...', 'en', 1),
('txtQuickJoinDesc', '[writer_count]/[max_writers] writers • [mode] mode', 'en', 1),

-- Story Add Form (ephemeral interactive message)
('txtCreateStoryTitle', 'Create New Story', 'en', 1),
('txtStoryAddIntro', 'Configure your story settings with the buttons below, then click Create Story when ready.', 'en', 1),
('txtStoryTitlePrompt', '⚠️ *Required — click below to set Story Title*', 'en', 1),
('txtNormalModeDesc', 'Writers get a private or public thread for each turn.', 'en', 1),
('txtQuickModeDesc', 'Writers submit entries via the /story write command.', 'en', 1),
('txtHideThreadsOffDesc', 'Turn threads are visible to all writers.', 'en', 1),
('txtHideThreadsOnDesc', 'Turn threads are private to the current writer only.', 'en', 1),
('txtStoryAddSessionExpired', 'Your story creation session has expired. Please run /story add again.', 'en', 1),
('btnSetTitle', 'Set Story Title', 'en', 1),
('btnSetTurnLength', 'Set Turn Length', 'en', 1),
('btnSetTimeout', 'Set Timeout Reminder Interval', 'en', 1),
('btnSetAO3Name', 'Set AO3 Name', 'en', 1),
('btnSetDelayHours', 'Set Delay Hours', 'en', 1),
('btnSetDelayWriters', 'Set Delay Writers', 'en', 1),
('btnCreateStory', '✅ Create Story', 'en', 1),
('lblModeToggle', 'Story Mode', 'en', 1),
('lblHideToggle', 'Hide Threads', 'en', 1),
('lblPrivateToggle', 'Keep My Turns Private', 'en', 1),
('txtPrivateOffDesc', 'Your turn threads will be visible to other writers.', 'en', 1),
('txtPrivateOnDesc', 'Your turn threads will only be visible to you and admins.', 'en', 1),
('lblDelayStart', 'Delay Start By', 'en', 1),
('txtDelayHint', 'leave blank to start immediately', 'en', 1),
('lblWriterOrder', 'Writer Order', 'en', 1),
('lblShowAuthors', 'Show Author Names', 'en', 1),
('txtShowAuthorsOnDesc', 'Writer names appear on entries in Discord and in the export file.', 'en', 1),
('txtShowAuthorsOffDesc', 'Entries are posted and exported anonymously.', 'en', 1),
('txtOrderRandom', 'Random', 'en', 1),
('txtOrderRoundRobin', 'Round Robin', 'en', 1),
('txtOrderFixed', 'Fixed Order', 'en', 1),
('txtOrderRandomDesc', 'Next writer is chosen completely at random each turn.', 'en', 1),
('txtOrderRoundRobinDesc', 'Writers rotate randomly, but no one repeats until everyone has had a turn.', 'en', 1),
('txtOrderFixedDesc', 'Writers take turns in a fixed sequence based on join order.', 'en', 1),

-- Admin Commands
('txtAdminOnly', '❌ You need admin permissions to use this command.', 'en', 1),
('txtAdminNoActiveTurn', 'There is no active turn in this story.', 'en', 1),
('txtAdminSkipSuccess', '✅ Turn skipped. The next writer has been notified.', 'en', 1),
('txtAdminExtendSuccess', '✅ Turn extended by [hours] hour(s). New deadline: [new_end_time].', 'en', 1),
('txtAdminKickNotWriter', '❌ [user_name] is not an active writer in this story.', 'en', 1),
('txtAdminKickSuccess', '✅ **[user_name]** has been removed from **[story_title]**.', 'en', 1),
('txtAdminPauseSuccess', '⏸️ **[story_title]** has been paused.', 'en', 1),
('txtAdminAlreadyPaused', 'This story is already paused.', 'en', 1),
('txtAdminAlreadyActive', 'This story is already active.', 'en', 1),
('txtAdminResumeSuccess', '▶️ **[story_title]** has been resumed.', 'en', 1),
('txtAdminDeleteConfirm', '⚠️ Are you sure you want to **permanently delete** "[story_title]"? All turns, entries, and writer data will be gone. This cannot be undone.', 'en', 1),
('btnConfirmDelete', '🗑️ Permanently Delete', 'en', 1),
('txtAdminDeleteSuccess', '✅ **[story_title]** has been permanently deleted.', 'en', 1),
('txtAdminConfigTitle', '⚙️ Story Settings — [story_title]', 'en', 1),
('txtAdminConfigSaved', '✅ Story settings saved.', 'en', 1),
('btnAdminConfigSave', '✅ Save Changes', 'en', 1),
('lblAllowLateJoins', 'Allow Late Joins', 'en', 1),

-- Story Manage
('lblOpenToWriters', 'Open to New Writers', 'en', 1),
('lblSummary', 'Story Summary', 'en', 1),
('btnSetSummary', 'Set Summary', 'en', 1),
('lblTags', 'Tags', 'en', 1),
('btnSetTags', 'Set Tags', 'en', 1),
('txtManageNotAuthorized', '❌ Only the story creator or an admin can manage this story.', 'en', 1),
('txtTurnThreadResumed', '▶️ **Story resumed.** Your turn deadline has been reset to [turn_end_time]. Use the buttons above to finalize or skip your turn when ready.', 'en', 1),

-- Admin Next
('txtAdminNextSuccess', '✅ **[user_name]** will receive the next turn.', 'en', 1),
('txtAdminNextAlreadyCurrent', '❌ **[user_name]** is already the current writer.', 'en', 1),

-- Story Thread Activity Log
('txtStoryThreadTurnStart', '✍️ **Turn [turn_number]:** It''s **[writer_name]**''s turn! Deadline: [turn_end_full] ([turn_end_relative]).', 'en', 1),
('txtStoryThreadTurnSkip', '⏭️ **[writer_name]** skipped their turn.', 'en', 1),
('txtStoryThreadTurnTimeout', '⏰ **[writer_name]**''s turn timed out and was automatically skipped.', 'en', 1),
('txtStoryThreadWriterJoin', '👋 **[writer_name]** joined the story.', 'en', 1),
('txtStoryThreadWriterRemove', '🚫 **[writer_name]** was removed from the story by an admin.', 'en', 1),

-- Skip turn confirmation
('txtSkipConfirmNoContent', '⏭️ **Skip your turn?** This will pass to the next writer without submitting an entry. This cannot be undone.', 'en', 1),
('txtSkipConfirmHasContent', '⚠️ **Skip your turn?** You have posted content in this thread — **it will be discarded** if you skip. This cannot be undone.', 'en', 1),
('btnSkipConfirm', 'Yes, Skip My Turn', 'en', 1),
('btnSkipCancel', 'Cancel', 'en', 1),

-- System Configuration
('cfgLanguageCode', 'en', 'en', 1),
('cfgEntryTimeoutMinutes', '10', 'en', 1),
('cfgStoryFeedChannelId', '1432779418631274566', 'en', 1),
('cfgAdminRoleName', 'Round Robin Admin', 'en', 1), -- Admin role name for story management
('cfgMediaChannelId', '1432779683497250867', 'en', 1), -- Channel for forwarded story images
('errProcessingRequest', 'An error occurred while processing your request.', 'en', 1);