-- Sample config entries for testing the story system
-- Insert default English config values for system (guild_id = 1)

INSERT INTO config (config_key, config_value, language_code, guild_id) VALUES

-- Field Labels
('lblStoryTitle', 'Story Title:', 'en', 1),
('lblQuickMode', 'Quick Mode?:', 'en', 1),
('lblTurnLength', 'Turn Length (hours):', 'en', 1),
('lblTimeoutReminder', 'Timeout Reminder Interval:', 'en', 1),
('lblHideTurnThreads', 'Hide Turn Threads?', 'en', 1),
('lblNoHours', 'By # of Hours (if applicable):', 'en', 1),
('lblNoWriters', '# of Writers (if applicable):', 'en', 1),
('lblMaxWriters', 'Max Writers (optional):', 'en', 1),
('btnSetMaxWriters', 'Max Writers: [max_writers]', 'en', 1),
('lblYourAO3Name', 'Your Pen Name:', 'en', 1),
('lblKeepYourPrivate', 'Keep your turn threads private?:', 'en', 1),

-- Text Messages
('txtDelayStoryStart', 'Delay Story Start? (leave blank to start immediately):', 'en', 1),
('txtAndOr', 'and/or', 'en', 1),
('txtStoryCreatorAdd', 'You''ll be added as the first writer in the story. Please provide:', 'en', 1),
('txtMustBeNo', '[Field label text] must be a number.', 'en', 1),
('txtStoryThreadTitle', 'Story ID: [story_id] - [inputStoryTitle] - [story_status]', 'en', 1),
('txtTurnThreadTitle', 'Story ID: [story_id] - Turn [storyTurnNumber] - [user display name] - Ends [turnEndTime]', 'en', 1),
('txtDMTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.\n-# Use `/mystory help` to see your writer commands.', 'en', 1),
('txtMentionTurnStart', '🎭 **Your turn has started!** You can now write your part of the story.\n-# Use `/mystory help` to see your writer commands.', 'en', 1),
('txtDMTurnReminder', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Your deadline is [turn_end_full] ([turn_end_relative]). Don''t forget to write your entry.', 'en', 1),
('txtMentionTurnReminder', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Your deadline is [turn_end_full] ([turn_end_relative]). Don''t forget to write your entry.', 'en', 1),
('txtNormalModeWelcome', '## Welcome to your turn thread for *[story_title]*\nWrite your story entry here in as many posts as you''d like. Edit as needed, and use Discord markdown for formatting. Use the buttons below to Finalize your turn, or Skip to pass to the next writer without submitting.\n\nYour turn ends on [turn_end_full], in [turn_end_relative].\n-# If you need to catch up with the story since your last turn, use the command `/mystory catchup story_id:[story_id]`.', 'en', 1),
('txtNormalModeWelcomeNoMedia', '## Welcome to your turn thread for *[story_title]*\nWrite your story entry here in as many posts as you''d like. Edit as needed, using Discord markdown for formatting. Use the buttons below to Finalize your turn, or Skip to pass to the next writer without submitting.\n\nYour turn ends on [turn_end_full], in [turn_end_relative].\n-# If you need to catch up with the story since your last turn, use the command `/mystory catchup story_id:[story_id]`.', 'en', 1),
('txtQuickModeTurnStart', '🎭 **[story_title]:** [current_writer]''s turn has started! Please use `/story write [story_id]` to submit your entry. Turn ends [turn_end_date].', 'en', 1),
('btnFinalizeEntry', '✅ Finalize Entry', 'en', 1),
('btnSkipTurn', '⏭️ Skip Turn', 'en', 1),
('btnViewLastEntry', '📖 View Last Entry', 'en', 1),
('btnJoinStory', '✋ Join This Story', 'en', 1),
('txtAlreadyJoined', 'You have already joined this story!', 'en', 1),
('txtStoryJoinFail', 'You were not added to the story. Please contact an administrator.', 'en', 1),
('txtStoryActive', 'Your story is now active!', 'en', 1),
('txtMoreWritersDelay', 'This story will begin when X more writer(s) join!', 'en', 1),
('txtHoursDelay', 'This story will begin in X hours!', 'en', 1),

-- Story Status Text
('txtClosed', 'Closed', 'en', 1),
('txtActive', 'Active', 'en', 1),
('txtPaused', 'Paused', 'en', 1),
('txtDelayed', 'Waiting to Start', 'en', 1),

-- Error Messages
('txtThreadCreationFailed', 'Failed to create story thread. Please contact the administrator.', 'en', 1),
('txtStoryCreated', 'Story created successfully!', 'en', 1),
('txtDMFailed', 'Could not send direct message. Check your privacy settings.', 'en', 1),

-- Write Command Text
('lblWriteEntry', 'Your Story Entry (up to 4000 characters)', 'en', 1),
('txtWriteWarning', 'TEXT IS NOT SAVED UNTIL SUBMITTED!', 'en', 1),
('txtWritePlaceholder', 'Paste your entry here...', 'en', 1),
('txtStoryNotActive', 'This story is not active. You cannot write entries for paused or closed stories.', 'en', 1),
('txtNormalModeWrite', 'This story is in normal mode. Please write your entry in your private turn thread.', 'en', 1),
('txtNotYourTurn', 'It is not your turn to write. Please wait for your turn.', 'en', 1),
('txtPendingEntryExists', 'You already have a pending entry. This will overwrite it. Continue?', 'en', 1),
('txtStoryNotFound', 'Story not found.', 'en', 1),
('txtStoryWrongGuild', 'Story not found in this server.', 'en', 1),
('txtWriteFormFailed', 'Failed to open write form. Please try again.', 'en', 1),
('txtEntryProcessFailed', 'Failed to process entry. Please try again.', 'en', 1),
('txtPreviewTitle', '📖 Entry Preview', 'en', 1),
('txtPreviewDescription', '**Review your entry before final submission:**', 'en', 1),
('txtPreviewExpires', '⏰ Expires', 'en', 1),
('lblYourEntry', '✍️ Your Entry:', 'en', 1),
('lblEntryContinued', '✍️ Continued ([count]):', 'en', 1),
('lblEntryStats', '📊 Entry Stats:', 'en', 1),
('txtEntryStatsTemplate', 'Characters: [char_count]/4000
Words: ~[word_count]', 'en', 1),
('btnSubmit', 'Submit', 'en', 1),
('btnDiscard', 'Discard', 'en', 1),
('txtEntrySubmitted', '✅ **Entry submitted successfully!** The turn will advance to the next writer.', 'en', 1),
('txtEntryDiscarded', '🗑️ **Entry discarded.** You can write a new entry by using the /story write command again.', 'en', 1),
('txtActionFailed', 'Failed to process action. Please try again.', 'en', 1),
('txtDMReminder', '📝 **Pending Entry Reminder** - You have an entry waiting for confirmation.', 'en', 1),
('txtRecoveryInstructions', 'If you lost the confirmation message, use `/story myturn pending` to recover it.', 'en', 1),
('txtEmptyEntry','You need to write something in the thread before finalizing your entry.', 'en', 1),
('txtNoActiveTurn','You do not have an active turn in this story.', 'en', 1),
('txtEntryFinalized','✅ Entry finalized successfully! The turn has been completed.', 'en', 1),
('txtSkipSuccess', '✅ Turn skipped. The next writer has been notified.', 'en', 1),
('txtFailedtoFinalize', 'Failed to finalize entry. Please try again.', 'en', 1),

-- Shared UI
('btnCancel', 'Cancel', 'en', 1),
('txtActionCancelled', 'Cancelled.', 'en', 1),
('txtActionSessionExpired', 'This confirmation has expired. Please run the command again.', 'en', 1),
('txtNotActiveWriter', 'You are not an active writer in this story.', 'en', 1),
('txtNoConfirmedEntries', 'This story has no finalized entries yet.', 'en', 1),

-- MyStory Dashboard
('txtMyStoriesTitle', '📚 Your Active Stories', 'en', 1),
('txtMyStoryNone', '🤷 You''re not currently a writer in any active stories. Use /story join to get started!', 'en', 1),
('txtMyTurnQuick', '🎯 **Your turn!** Use `/story write [story_id]`', 'en', 1),
('txtMyTurnNormal', '🎯 **Your turn!**', 'en', 1),
('txtOthersTurn', '✍️ [writer_name]''s turn', 'en', 1),
('txtMyTurnHistory', '↩️ Last turn [last_turn_at] · [turn_count] turn(s)', 'en', 1),
('txtMyTurnNoHistory', '↩️ No turns yet', 'en', 1),

-- MyStory Catchup
('txtCatchupNoEntries', 'No new entries since your last turn.', 'en', 1),
('txtCatchupSessionExpired', 'Session expired. Please run `/mystory catchup` again.', 'en', 1),

-- MyStory Manage panel
('txtMyStoryManageTitle', 'My Settings — **[story_title]**', 'en', 1),
('lblMyStoryManageAO3', 'Pen Name', 'en', 1),
('lblMyStoryManageNotif', 'Notifications', 'en', 1),
('lblMyStoryManagePrivacy', 'Turn Privacy', 'en', 1),
('txtMyStoryManageSaved', '✅ Your settings have been saved.', 'en', 1),
('btnMyStoryManageSave', '✅ Save Changes', 'en', 1),

-- MyStory Leave
('txtLeaveConfirm', '⚠️ Are you sure you want to leave **[story_title]**? This cannot be undone.', 'en', 1),
('txtLeaveConfirmMyTurn', '⚠️ It''s currently your turn in **[story_title]**. Leaving will skip your turn. Are you sure?', 'en', 1),
('txtLeaveConfirmLastWriter', '⚠️ You are the **last active writer** in **[story_title]**. Leaving will automatically close the story. Are you sure?', 'en', 1),
('btnLeaveStory', 'Leave Story', 'en', 1),
('txtLeftStorySuccess', '✅ You have left the story.', 'en', 1),

-- MyStory Pass
('txtPassSuccess', '✅ Your turn has been passed.', 'en', 1),

-- MyStory Pause / Resume
('txtNoActiveStoriesToPause', 'You are not an active writer in any stories right now.', 'en', 1),
('txtPauseSuccess', '✅ You have been paused. Check your DMs for a summary.', 'en', 1),
('txtPauseDM', 'You have been paused in the following stories:\n[story_list]\n\nWhen you''re ready to jump back in, use [resume_command]. Note that pausing does not remove you from the story — to leave permanently, use /mystory leave.', 'en', 1),
('txtResumeSuccess', '✅ You are back in the rotation. You will be included in the selection of writers the next time a turn starts.', 'en', 1),
('txtNotPaused', 'You are not currently paused in any stories.', 'en', 1),
('txtWriterStatusPaused', '⏸ You are paused in this story — use /mystory resume to rejoin the rotation.', 'en', 1),

-- Close Story Text
('txtStoryAlreadyClosed', 'This story is already closed.', 'en', 1),
('txtStoryNotFoundOrClosed', 'Story not found or already closed.', 'en', 1),
('txtStoryCloseNotAuthorized', 'You do not have permission to close this story. Only the story creator or an admin can close a story.', 'en', 1),
('txtStoryCloseConfirm', '⚠️ Are you sure you want to close **[story_title]**? The active turn will be ended. This cannot be undone.', 'en', 1),
('btnCloseConfirm', '🔒 Close Story', 'en', 1),
('txtStoryClosedPublic', '📕 **[story_title]** is now complete! Thank you to all [writer_count] writer(s) who participated — [turn_count] turns and ~[word_count] words. The full story is attached below.', 'en', 1),
('txtStoryFeedClosed', '🎉 **Congratulations to the writers of [story_title]!** The story has concluded with [turn_count] turns and ~[word_count] words. Thank you to all [writer_count] writer(s)! The full story is attached below.', 'en', 1),

-- Story List Text
('txtAllStories', 'All Stories', 'en', 1),
('txtJoinableStories', 'Joinable Stories', 'en', 1),
('txtMyStories', 'My Stories', 'en', 1),
('txtActiveStories', 'Active Stories', 'en', 1),
('txtPausedStories', 'Paused Stories', 'en', 1),
('txtNoStoriesFound', '📚 **No stories found** for filter "[filter_name]"', 'en', 1),
('txtStoriesPageTitle', '📚 [filter_title] (Page [page]/[total_pages])', 'en', 1),
('txtStoriesPageDesc', 'Showing [showing] of [total] stories', 'en', 1),
('txtMemberStatusCanJoin', '🟢 Can Join', 'en', 1),
('txtMemberStatusCanNotJoin', '🔴 Cannot Join', 'en', 1),
('txtMemberStatusJoined', '✅ Joined', 'en', 1),
('txtStoryListFailed', 'Failed to load stories. Please try again.', 'en', 1),
('lblStoryStatus', 'Status:', 'en', 1),
('lblStoryTurn', 'Turn:', 'en', 1),
('lblStoryWriters', 'Writers:', 'en', 1),
('lblStoryMode', 'Mode:', 'en', 1),
('lblStoryCreator', 'Creator:', 'en', 1),
('txtModeQuick', 'Quick', 'en', 1),
('txtModeNormal', 'Normal', 'en', 1),
('txtTurnWaiting', 'Waiting to start', 'en', 1),
('txtTurnOverdue', '[writer_name] (overdue)', 'en', 1),
('txtTurnTimeLeft', '[writer_name] ([hours]h left)', 'en', 1),
('txtTurnUnknown', 'Unknown', 'en', 1),

-- Join Command Text  
('lblJoinAO3Name', 'Pen Name (optional)', 'en', 1),
('lblJoinPrivacySelect', 'Turn Thread Privacy', 'en', 1),
('lblJoinNotifSelect', 'Notifications', 'en', 1),
('txtJoinEmbedDesc', 'Choose your preferences below, then click **Confirm Join**. You can update these later from your story settings.', 'en', 1),
('txtJoinAO3NotSet', 'Not set — will use your Discord display name', 'en', 1),
('btnJoinSetAO3', 'Set Pen Name', 'en', 1),
('btnJoinConfirm', '✅ Confirm Join', 'en', 1),
('txtJoinSuccess', '✅ Successfully joined "[story_title]"! You are writer #[writer_number].', 'en', 1),
('txtJoinStoryFull', '❌ This story has reached its maximum of [max_writers] writers.', 'en', 1),
('txtJoinNotAllowed', '❌ This story does not allow new writers to join after it has started.', 'en', 1),
('txtJoinStoryClosed', '❌ This story is closed and not accepting new writers.', 'en', 1),
('txtStoryFeedJoinAnnouncement', '🎭 **[joiner_name]** just joined **[story_title]**! It\'s currently **[current_writer]**\'s turn until [turn_end_date].', 'en', 1),
('txtStoryFeedJoinAnnouncementNoTurn', '🎭 **[joiner_name]** just joined **[story_title]**!', 'en', 1),
('txtStoryFeedNowActive', '🎬 **[story_title] is now active!** [first_writer] will start the story. Turn ends [turn_end_date].', 'en', 1),
('txtStoryFeedTurnStart', '✍️ **[story_title]:** [current_writer]''s turn has started! Turn ends [turn_end_date].', 'en', 1),
('txtJoinFormFailed', 'Failed to open join form. Please try again.', 'en', 1),
('txtJoinProcessFailed', 'Failed to process join request. Please try again.', 'en', 1),
('txtValidationErrors', '**Validation Errors:**', 'en', 1),
('txtPrivacyValidation', 'Keep Private must be "yes" or "no".', 'en', 1),
('txtQuickModeValidation', 'Quick Mode must be "off" or "on".', 'en', 1),
('txtTimeoutReminderValidation', 'Timeout Reminder must be a number between 0 and 100.', 'en', 1),
('txtHideTurnThreadsValidation', 'Hide Turn Threads must be "off" or "on".', 'en', 1),
('txtFormOpenError', 'Failed to open story creation form. Please try again.', 'en', 1),
('txtFormProcessError', 'Failed to process form. Please try again.', 'en', 1),
('txtAdditionalOptionsError', 'Failed to show additional options form.', 'en', 1),
('txtStoryCreationError', 'Failed to create story. Please try again.', 'en', 1),
('txtNotificationValidation', 'Notification Preference must be "dm" or "mention".', 'en', 1),
('txtJoinPrivacyPlaceholder', 'Enter: public or private', 'en', 1),
('txtJoinNotificationPlaceholder', 'Enter: dm or mention', 'en', 1),
('txtJoinAO3Placeholder', 'Leave blank to use Discord display name', 'en', 1),
('txtQuickModePlaceholder', 'Enter: off or on', 'en', 1),
('txtTurnLengthPlaceholder', 'Enter number of hours', 'en', 1),
('txtTimeoutReminderPlaceholder', 'Enter: 0, 25, 50, or 75', 'en', 1),
('txtHideTurnThreadsPlaceholder', 'Enter: off or on', 'en', 1),
('txtDelayHoursPlaceholder', 'Enter number of hours (optional)', 'en', 1),
('txtDelayWritersPlaceholder', 'Enter number of writers (optional)', 'en', 1),
('txtAO3NamePlaceholder', 'Your pen name (optional)', 'en', 1),
('txtKeepPrivatePlaceholder', 'Enter: yes or no', 'en', 1),
('btnPrev', '◀️ Prev', 'en', 1),
('btnNext', 'Next ▶️', 'en', 1),
('btnFilter', '🔍 Filter', 'en', 1),
('txtQuickJoinPlaceholder', 'Quick join a story...', 'en', 1),
('txtQuickJoinDesc', '[writer_count]/[max_writers] writers • [mode] mode', 'en', 1),

-- Story Add Form (ephemeral interactive message)
('txtCreateStoryTitle', 'Create New Story', 'en', 1),
('txtStoryAddIntro', 'Configure your story settings with the buttons below, then click Create Story when ready.', 'en', 1),
('txtStoryTitlePrompt', '⚠️ *Required — click below to set Story Title*', 'en', 1),
('txtNormalModeDesc', 'Writers get a private or public thread for each turn.', 'en', 1),
('txtQuickModeDesc', 'Writers submit entries via the /story write command.', 'en', 1),
('txtHideThreadsOffDesc', 'Turn threads are visible to all writers.', 'en', 1),
('txtHideThreadsOnDesc', 'Turn threads are private to the current writer only.', 'en', 1),
('txtStoryAddSessionExpired', 'Your story creation session has expired. Please run /story add again.', 'en', 1),
('btnSetTitle', 'Set Story Title', 'en', 1),
('btnSetTurnLength', 'Turn Length: [turn_length]', 'en', 1),
('btnSetTimeout', 'Reminder Interval: [reminder_interval]', 'en', 1),
('btnSetAO3Name', 'Set Pen Name', 'en', 1),
('btnSetDelayHours', 'Set Delay Hours', 'en', 1),
('btnSetDelayWriters', 'Set Delay Writers', 'en', 1),
('btnCreateStory', '✅ Create Story', 'en', 1),
('lblModeToggle', 'Story Mode', 'en', 1),
('lblHideToggle', 'Hide Threads', 'en', 1),
('btnAddHideToggle', 'Hide My Threads', 'en', 1),
('lblPrivateToggle', 'Turns', 'en', 1),
('txtPrivateOffDesc', 'Your turn threads will be visible to other writers.', 'en', 1),
('txtPrivateOnDesc', 'Your turn threads will only be visible to you and admins.', 'en', 1),
('lblDelayStart', 'Delay Start By', 'en', 1),
('txtDelayHint', 'leave blank to start immediately', 'en', 1),
('lblWriterOrder', 'Writer Order', 'en', 1),
('lblShowAuthors', 'Show Names', 'en', 1),
('txtShowAuthorsOnDesc', 'Writer names appear on entries in Discord and in the export file.', 'en', 1),
('txtShowAuthorsOffDesc', 'Entries are posted and exported anonymously.', 'en', 1),
('txtOrderRandom', 'Random', 'en', 1),
('txtOrderRoundRobin', 'Round Robin', 'en', 1),
('txtOrderFixed', 'Fixed Order', 'en', 1),
('txtOrderRandomDesc', 'Next writer is chosen completely at random each turn.', 'en', 1),
('txtOrderRoundRobinDesc', 'Writers rotate randomly, but no one repeats until everyone has had a turn.', 'en', 1),
('txtOrderFixedDesc', 'Writers take turns in a fixed sequence based on join order.', 'en', 1),

-- Help Page 1
('txtHelp1Title', '📖 Round Robin StoryBot Overview', 'en', 1),
('txtHelp1Footer', 'Page 1 of 3 · Story IDs appear in /story list and in story thread titles.', 'en', 1),
('btnHelp1ToPage2', '📝 Story Creation Guide →', 'en', 1),
('lblHelp1FindJoin', '📚 Find & Join a Story', 'en', 1),
('txtHelp1FindJoin', 'Use `/story list` to browse all of the stories on the server, past or present. Stories have dedicated threads for all of their activity, and those can be found by clicking the 🧵 icon in the Round Robin feed channel.\n\nWhen you''re ready, you can join a story in several ways:\n- Use the quick join menu on `/story list`\n- Type `/story join [id]`\n- Navigate to the story thread and click the "✍️ Join This Story" button on the pinned story info post at the top of the thread.', 'en', 1),
('lblHelp1JoiningOptions', '⚙️ Joining Options', 'en', 1),
('txtHelp1JoiningOptions', '**Turn Thread Privacy** *(only applies to Normal Mode stories)*\n- 🌐 **Public** — Threads for your turns will be visible to all members of your server.\n- 🔒 **Private** — Turn threads will be private and only visible to you and server admins.\n\n**Notifications**\n- 💬 **DM** — StoryBot will send you a DM for turn start, reminders, and turn timeout or skip.\n- 📢 **Mention in channel** — You will be tagged in messages from the bot posted in the story thread.\n\n**Pen Name** *(optional)*\n- ✍️ The name that will appear on the list of writers on the story. If the story is configured to display names, it will also show on entries and in the exported story. This field fills in your Discord display name by default.', 'en', 1),
('lblHelp1Dashboard', '🗂️ Your Dashboard', 'en', 1),
('txtHelp1Dashboard', 'Use `/mystory list` to see all the stories you''ve joined — active, paused, delayed, and closed.', 'en', 1),
('lblHelp1ManageParticipation', '🤝 Managing Your Participation', 'en', 1),
('txtHelp1ManageParticipation', 'Use `/mystory manage` to take action on a specific story:\n- Pass your current turn\n- Pause or resume your participation\n- Leave the story', 'en', 1),
('lblHelp1WriteNormal', '✍️ Writing Your Turn — Normal Mode', 'en', 1),
('txtHelp1WriteNormal', 'When it''s your turn, you''ll be notified with a link to your turn thread. Type as many posts as you like, add images in their own posts with display (alt) text (if images are enabled on your server), and format your posts using Discord markdown for bold, italics, etc. If you want to review the entries in the story since you last wrote, use `/mystory catchup` to see your last entry and the entries since.\n\nYour entry won''t be posted until you click Finalize — you can revise as much as you like first. *All* of your posts in the turn thread will be compiled for your entry, so make sure you delete any of your own chatter before finalizing. Posts from the bot or other users will not be included. If you need more time, you can click a button on the first post in the thread to request an extension from the story creator.', 'en', 1),
('txtHelp1WriteNormalNoMedia', 'When it''s your turn, you''ll be notified with a link to your turn thread. Type as many posts as you like and format your posts using Discord markdown for bold, italics, etc. If you want to review the entries in the story since you last wrote, use `/mystory catchup` to see your last entry and the entries since.\n\nYour entry won''t be posted until you click Finalize — you can revise as much as you like first. *All* of your posts in the turn thread will be compiled for your entry, so make sure you delete any of your own chatter before finalizing. Posts from the bot or other users will not be included. If you need more time, you can click a button on the first post in the thread to request an extension from the story creator.', 'en', 1),
('lblHelp1WriteQuick', '⚡ Writing Your Turn — Quick Mode', 'en', 1),
('txtHelp1WriteQuick', 'If a story is in Quick Mode, you won''t get a thread for your turn. You can post an entry by typing `/story write`. Entries are limited to 4,000 characters, and images are not supported. Your entry is posted immediately when you submit — there''s no draft or finalize step.', 'en', 1),

-- Help Page 2
('txtHelp2Title', '📝 Create New Story — Option Reference', 'en', 1),
('txtHelp2Footer', 'Page 2 of 3 · After story creation, these settings can be edited by admins or the story creator via `/story manage.`', 'en', 1),
('btnHelp2ToPage1', '← Back to Overview', 'en', 1),
('btnHelp2ToPage3', '⚙️ Story Manage Guide →', 'en', 1),
('lblHelp2StoryTitle', 'Story Title', 'en', 1),
('txtHelp2StoryTitle', '- ⚠️ *Required.*', 'en', 1),
('lblHelp2MaxWriters', 'Max Writers', 'en', 1),
('txtHelp2MaxWriters', '- #️⃣ Optional. Leave blank for no limit.', 'en', 1),
('lblHelp2TurnLength', 'Turn Length', 'en', 1),
('txtHelp2TurnLength', '- ⌛ How many hours each writer has per turn. Default: 24h.', 'en', 1),
('lblHelp2StoryMode', 'Story Mode', 'en', 1),
('txtHelp2StoryMode', '- 🟢 **Normal** — Writers get a private or public thread for each turn.\n- 🟣 **Quick** — Writers submit entries via `/story write`.', 'en', 1),
('lblHelp2WriterOrder', 'Writer Order', 'en', 1),
('txtHelp2WriterOrder', '- 🎲 **Random** — Next writer chosen completely at random each turn.\n- 🔄 **Round Robin** — Rotates randomly, but no one repeats until everyone has had a turn.\n- 📋 **Fixed Order** — Writers take turns in a fixed sequence based on join order.', 'en', 1),
('lblHelp2HideThreads', 'Hide Threads', 'en', 1),
('txtHelp2HideThreads', '- 🥷 **On** — Turn threads are private to the current writer and admins only.\n- 🤡 **Off** — Turn threads are visible to all server members.', 'en', 1),
('lblHelp2ShowAuthors', 'Show Author Names', 'en', 1),
('txtHelp2ShowAuthors', '- 📑 **Yes** — Writer names appear on entries in Discord and in the export file.\n- 📄 **No** — Entries are posted and exported anonymously.', 'en', 1),
('lblHelp2TimeoutReminder', 'Timeout Reminder', 'en', 1),
('txtHelp2TimeoutReminder', '- ⏰ Send a reminder to the current writer after X% of their turn has elapsed. Default: 50%. Set to 0% to disable.', 'en', 1),
('lblHelp2DelayStart', 'Delay Start By', 'en', 1),
('txtHelp2DelayStart', '- 🫸 Leave blank to start immediately. Set a number of hours, a minimum writer count, or both — the story activates when all conditions are met.', 'en', 1),
('lblHelp2CreatorOptions', 'Story Creator''s Join Options', 'en', 1),
('txtHelp2CreatorOptions', '**Your Pen Name**\n- ✍️ Your name as it will appear on the story. Used in story exports. Defaults to your Discord display name if left blank.\n\n**Keep My Turns Private**\n- 🔒 **Yes** — Your turn threads will only be visible to you and admins.\n- 🔓 **No** — Your turn threads will be visible to other writers.', 'en', 1),

-- Help Page 3
('txtHelp3Title', '⚙️ Managing a Story — /story manage', 'en', 1),
('txtHelp3Footer', 'Page 3 of 3', 'en', 1),
('btnHelp3ToPage2', '← Story Creation Guide', 'en', 1),
('lblHelp3WhoCanUse', 'Who can use /story manage?', 'en', 1),
('txtHelp3WhoCanUse', 'The story creator (the first writer to join) and server admins.', 'en', 1),
('lblHelp3WhatEdit', 'What can be edited?', 'en', 1),
('txtHelp3WhatEdit', '**Story settings** (via `/story manage`):\n- **Turn Length** — How many hours each writer has per turn.\n- **Timeout Reminder** — What % into a turn to send the writer a reminder. Set to 0% to disable.\n- **Max Writers** — Cap on total writers. Leave blank for no limit.\n- **Open to New Writers** — Allows new writers to join.\n- **Show Author Names** — Writer names appear on entries and in the story export if enabled.\n- **Writer Order** — Choose between Random, Round Robin, and Fixed (Join) Order.\n- **Turn Privacy** — Private turns are only visible to the current writer (and admins via channel permissions). Public turns are visible to all.\n- **Summary** — A freeform description used in story exports.\n- **Tags** — Comma-separated tag list used in story exports.\n\n**Entry content** — Use `/story edit [id]` to edit the text of a finalized entry. Writers can edit their own entries; admins can edit any.', 'en', 1),
('lblHelp3PauseResume', 'Pausing and Resuming', 'en', 1),
('txtHelp3PauseResume', '- Sets the story status to paused (freezing the current turn) or resumes a paused story. Resuming starts the next turn automatically if no turn is currently active.\n- Use the button in `/story manage` to pause or resume.', 'en', 1),
('lblHelp3Closing', 'Closing a Story', 'en', 1),
('txtHelp3Closing', '- Use `/story close [id]` to permanently close a story. This posts a completion message with the full story export and ends the current turn, but leaves the story thread open for discussion. This cannot be undone.', 'en', 1),
('lblHelp3AdminControls', 'Admin Controls', 'en', 1),
('txtHelp3AdminControls', '- Skip the current turn\n- Extend the current turn\n- Set the writer who will be selected when the next turn starts\n- Remove a writer from a story\n- Delete a story', 'en', 1),

-- /mystory help
('txtMyHelpTitle', '📋 Writer Command Reference', 'en', 1),
('txtMyHelpFooter', 'For story creation, modes, and settings — use /story help', 'en', 1),
('lblMyHelpDashboard', '📊 Your Dashboard', 'en', 1),
('txtMyHelpDashboard', '- `/mystory active` — Your active stories and whose turn it is\n- `/mystory history` — All stories you''ve ever been in\n- `/mystory catchup [id]` — Read entries written since your last turn', 'en', 1),
('lblMyHelpTurn', '✍️ Your Turn', 'en', 1),
('txtMyHelpTurn', '- `/story write [id]` — Submit your entry *(quick mode)*\n- `/story read [id]` — Read the story in Discord\n- `/story edit [id]` — Edit one of your finalized entries\n- `/mystory pass [id]` — Skip your current turn\n- `/mystory leave [id]` — Leave a story', 'en', 1),
('lblMyHelpPause', '⏸️ Pausing', 'en', 1),
('txtMyHelpPause', '- `/mystory pause [id]` — Step out of the turn rotation temporarily. Omit the ID to pause all of your active stories at once. If it''s your turn when you pause, it will be passed automatically. To leave the story permanently, use `/mystory leave [id]`.\n- `/mystory resume [id]` — Rejoin the rotation. You''ll re-enter the order of writers as before, depending on story settings.', 'en', 1),

-- Storyadmin Help
('txtAdminHelpTitle', '⚙️ StoryAdmin Commands', 'en', 1),
('txtAdminHelpFooter', 'Story settings (pause, resume, turn length, writer order) are managed via /story manage. All commands require the round robin admin role specified at server setup or the Discord Administrator role.', 'en', 1),
('lblAdminHelpSkip', '/storyadmin skip [story_id]', 'en', 1),
('txtAdminHelpSkip', 'Force-ends the active turn and advances to the next writer. If it is a normal mode story it will delete the active thread.', 'en', 1),
('lblAdminHelpExtend', '/storyadmin extend [story_id] [hours]', 'en', 1),
('txtAdminHelpExtend', 'Adds hours to the current turn deadline.', 'en', 1),
('lblAdminHelpManageUser', '/storyadmin manage [story_id] [user]', 'en', 1),
('txtAdminHelpManageUser', 'Opens a management panel. Without a user specified it will show story management settings (same as `/story manage`). With a user, it opens a user management panel — pause, unpause, remove, or update their pen name using buttons.', 'en', 1),
('lblAdminHelpNext', '/storyadmin next [story_id] [user]', 'en', 1),
('txtAdminHelpNext', 'Designates who will receive the next turn. If no turn is currently active, starts their turn immediately. Otherwise, the override takes effect when the current turn ends.', 'en', 1),
('lblAdminHelpReassign', '/storyadmin reassign [story_id]', 'en', 1),
('txtAdminHelpReassign', 'Reassigns the active turn to the previous writer (for example, they missed their turn and still want to write), then queues the current writer who was skipped so that they get the next turn and the order proceeds as normal.', 'en', 1),
('lblAdminHelpDelete', '/storyadmin delete [story_id]', 'en', 1),
('txtAdminHelpDelete', 'Permanently deletes a story and all its turns, entries, and writer data. Requires confirmation.', 'en', 1),
('lblAdminHelpSetup', '/storyadmin setup', 'en', 1),
('txtAdminHelpSetup', 'Configure Round Robin StoryBot for this server — set the story feed channel, media channel, and admin role name.', 'en', 1),

-- Storyadmin Setup panel
('txtSetupPanelTitle', 'Round Robin StoryBot Setup', 'en', 1),
('txtSetupRequiredAdmin', '⚠️ **Round Robin StoryBot has not been configured for this server.** Please run `/storyadmin setup` to set the story feed channel and admin role before using any other commands.', 'en', 1),
('txtSetupRequiredUser', '⚠️ **Round Robin StoryBot has not been configured for this server yet.** Please ask a server admin to run `/storyadmin setup`.', 'en', 1),
('txtSetupNoPermission', '❌ You need the Manage Server permission to configure Round Robin StoryBot.', 'en', 1),
('txtSetupFeedChannelInvalid', '❌ Could not find a feed channel with that ID. Please check and try again.', 'en', 1),
('txtSetupMediaChannelInvalid', '❌ Could not find a media channel with that ID. Please check and try again.', 'en', 1),
('txtSetupBotPermsFix', '_## To fix: Edit Channel Permissions to enable the permissions listed above for the [bot_role_name] member profile, not just the role._', 'en', 1),
-- Setup panel buttons
('btnSetupFeed', 'Set Feed Channel', 'en', 1),
('btnSetupMedia', 'Set Media Channel', 'en', 1),
('btnSetupRole', 'Set Admin Role', 'en', 1),
('btnSetupRestrictedFeed', 'Set Restricted Feed Channel', 'en', 1),
('btnSetupRestrictedMedia', 'Set Restricted Media Channel', 'en', 1),
('btnSetupRoundupChannel', 'Set Roundup Channel', 'en', 1),
('btnSetupRoundupDay', 'Set Roundup Day', 'en', 1),
('btnSetupRoundupHour', 'Set Roundup Hour', 'en', 1),
('btnSetupSave', 'Save Settings', 'en', 1),
-- Setup embed field descriptions (shown in italics below field name, above current value)
('txtSetupEmbedDescFeed', '-# This is where all story threads and activity will be posted.', 'en', 1),
('txtSetupEmbedDescMedia', '-# A private channel for story images. If blank, image handling in stories is disabled.', 'en', 1),
('txtSetupEmbedDescAdminRole', '-# Optional. If blank, only Discord server admins can use storyadmin commands.', 'en', 1),
('txtSetupEmbedDescRestrictedFeed', '-# Should be age-restricted if your server is not 18+.', 'en', 1),
('txtSetupEmbedDescRestrictedMedia', '-# Should be private and age-restricted.', 'en', 1),
('txtSetupEmbedDescRoundupChannel', '-# Where the weekly activity summary is posted. Leave blank to disable.', 'en', 1),
('txtSetupEmbedDescRoundupDay', '-# Day of the week to post (0 = Sunday, 6 = Saturday).', 'en', 1),
('txtSetupEmbedDescRoundupHour', '-# Hour to post in UTC (0–23).', 'en', 1),
('txtSetupModalSaveWarning', '``` === You Must Click Save Settings to Apply Changes! === ```', 'en', 1),
-- Setup modal titles (≤45 chars)
('txtSetupModalTitleFeed', 'Story Feed Channel', 'en', 1),
('txtSetupModalTitleMedia', 'Media/Image Channel', 'en', 1),
('txtSetupModalTitleRole', 'Admin Role', 'en', 1),
('txtSetupModalTitleRestrictedFeed', 'Restricted Feed Channel', 'en', 1),
('txtSetupModalTitleRestrictedMedia', 'Restricted Media Channel', 'en', 1),
('txtSetupModalTitleRoundupChannel', 'Weekly Roundup Channel', 'en', 1),
('txtSetupModalTitleRoundupDay', 'Weekly Roundup Day', 'en', 1),
('txtSetupModalTitleRoundupHour', 'Weekly Roundup Hour', 'en', 1),
-- Setup modal field labels (≤45 chars) and placeholders (≤100 chars)
('lblSetupModalFieldFeed', 'Story Feed Channel', 'en', 1),
('txtSetupModalPlaceholderFeed', 'Channel #name or ID (required)', 'en', 1),
('lblSetupModalFieldMedia', 'Media/Image Channel', 'en', 1),
('txtSetupModalPlaceholderMedia', 'Channel #name or ID (private, optional)', 'en', 1),
('lblSetupModalFieldRole', 'Admin Role Name', 'en', 1),
('txtSetupModalPlaceholderRole', 'Exact role name, case-sensitive (optional)', 'en', 1),
('lblSetupModalFieldRestrictedFeed', 'Restricted Feed Channel', 'en', 1),
('txtSetupModalPlaceholderRestrictedFeed', 'Channel #name or ID (restricted, optional)', 'en', 1),
('lblSetupModalFieldRestrictedMedia', 'Restricted Media Channel', 'en', 1),
('txtSetupModalPlaceholderRestrictedMedia', 'Channel #name or ID (restricted, optional)', 'en', 1),
('lblSetupModalFieldRoundupChannel', 'Roundup Channel', 'en', 1),
('txtSetupModalPlaceholderRoundupChannel', 'Channel #name or ID. Leave blank to disable.', 'en', 1),
('lblSetupModalFieldRoundupDay', 'Day of Week (0=Sun, 1=Mon … 6=Sat)', 'en', 1),
('txtSetupModalPlaceholderRoundupDay', 'Enter 0–6 (default: 1 = Monday)', 'en', 1),
('lblSetupModalFieldRoundupHour', 'Hour (UTC, 0–23)', 'en', 1),
('txtSetupModalPlaceholderRoundupHour', 'Enter 0–23 (default: 9 = 9:00 AM UTC)', 'en', 1),
('txtSetupRoundupDayInvalid', '❌ Day must be a number between 0 (Sunday) and 6 (Saturday).', 'en', 1),
('txtSetupRoundupHourInvalid', '❌ Hour must be a number between 0 and 23 (UTC).', 'en', 1),

-- Admin Commands
('txtAdminOnly', '❌ You need admin permissions to use this command.', 'en', 1),
('txtAdminNoActiveTurn', 'There is no active turn in this story.', 'en', 1),
('txtAdminSkipSuccess', '✅ Turn skipped. The next writer has been notified.', 'en', 1),
('txtAdminExtendSuccess', '✅ Turn extended by [hours] hour(s). New deadline: [new_end_time].', 'en', 1),
('txtAdminKickNotWriter', '❌ [user_name] is not an active writer in this story.', 'en', 1),
('txtAdminKickSuccess', '✅ **[user_name]** has been removed from **[story_title]**.', 'en', 1),
('txtAdminPauseUserSuccess', '✅ **[user_name]** has been paused in **[story_title]**.', 'en', 1),
('txtAdminUnpauseUserSuccess', '✅ **[user_name]** has been returned to active rotation in **[story_title]**.', 'en', 1),
('txtAdminUnpauseNotPaused', '❌ [user_name] is not currently paused in this story.', 'en', 1),
('txtAdminAO3NameSuccess', '✅ Pen name for **[user_name]** updated to **[ao3_name]**.', 'en', 1),

-- Storyadmin manageuser confirmation embeds
('txtAdminMUPauseConfirmDesc', '**[user_name]** will be temporarily removed from the turn rotation in **[story_title]**. They can rejoin at any time with /mystory resume.', 'en', 1),
('txtAdminMUUnpauseConfirmDesc', '**[user_name]** will be returned to active rotation in **[story_title]** and will be selected the next time the cycle reaches them.', 'en', 1),
('txtAdminMURemoveConfirmDesc', '**[user_name]** will be permanently removed from **[story_title]**. This cannot be undone.', 'en', 1),
('txtAdminMUActiveTurnWarning', '⚠️ It is currently **[user_name]**''s turn. Confirming will auto-pass to the next writer.', 'en', 1),
('txtAdminMULastWriterWarning', '🔴 **[user_name]** is the last active writer. Removing them will automatically close the story.', 'en', 1),
('btnAdminMUPause', '⏸️ Pause', 'en', 1),
('btnAdminMUUnpause', '▶️ Restore', 'en', 1),
('btnAdminMURemove', 'Remove', 'en', 1),
('btnAdminMUAO3Name', 'Update Name', 'en', 1),
-- Storyadmin manage writer panel
('txtManageUserPanelTitle', 'Managing **[writer_name]** in **[story_title]**', 'en', 1),
('lblManageUserStatus', 'Status', 'en', 1),
('lblManageUserAO3', 'Pen Name', 'en', 1),
('lblManageUserNotif', 'Notifications', 'en', 1),
('lblManageUserPrivacy', 'Turn Privacy', 'en', 1),
('btnManageUserClose', 'Close', 'en', 1),
('txtAdminPauseSuccess', '⏸️ **[story_title]** has been paused.', 'en', 1),
('txtAdminAlreadyPaused', 'This story is already paused.', 'en', 1),
('txtAdminAlreadyActive', 'This story is already active.', 'en', 1),
('txtAdminResumeSuccess', '▶️ **[story_title]** has been resumed.', 'en', 1),
('txtAdminDeleteConfirm', '⚠️ Are you sure you want to **permanently delete** "[story_title]"? All turns, entries, and writer data will be gone. This cannot be undone.', 'en', 1),
('btnConfirmDelete', '🗑️ Permanently Delete', 'en', 1),
('txtAdminDeleteSuccess', '✅ **[story_title]** has been permanently deleted.', 'en', 1),
('txtAdminDeleteEntryAlreadyDeleted', 'This entry has already been deleted.', 'en', 1),
('txtAdminDeleteEntrySuccess', 'Entry by **[author_name]** has been deleted. Entry ID: `[entry_id]` — to restore, use `/storyadmin restoreentry entry_id:[entry_id]`.', 'en', 1),
('txtAdminRestoreEntryNotDeleted', 'That entry is not deleted — nothing to restore.', 'en', 1),
('txtAdminRestoreEntrySuccess', 'Entry by **[author_name]** has been restored and will appear in `/story read` and exports again.', 'en', 1),
('txtAdminConfigTitle', '⚙️ Story Settings — [story_title]', 'en', 1),
('txtAdminConfigSaved', '✅ Story settings saved.', 'en', 1),
('btnAdminConfigSave', '✅ Save Changes', 'en', 1),
('lblAllowLateJoins', 'Allow Late Joins', 'en', 1),

-- Story Manage
('lblOpenToWriters', 'Allow Joins', 'en', 1),
('lblSummary', 'Story Summary', 'en', 1),
('btnSetSummary', 'Set Summary', 'en', 1),
('lblTags', 'Tags', 'en', 1),
('btnSetTags', 'Set Tags', 'en', 1),
('txtManageNotAuthorized', '❌ Only the story creator or an admin can manage this story.', 'en', 1),
('txtManageValidationTurnLength', 'Turn length must be at least 1 hour.', 'en', 1),
('txtManageValidationTimeout', 'Timeout reminder must be a number between 0 and 100.', 'en', 1),
('txtManageValidationMaxWriters', 'Max writers must be at least 1, or leave blank for no limit.', 'en', 1),
('txtTurnThreadResumed', '▶️ **Story resumed.** Your turn deadline has been reset to [turn_end_time]. Use the buttons above to finalize or skip your turn when ready.', 'en', 1),

-- Admin Next
('txtAdminNextSuccess', '✅ **[user_name]** will receive the next turn.', 'en', 1),
('txtAdminNextAlreadyCurrent', '❌ **[user_name]** is already the current writer.', 'en', 1),

-- Admin Reassign
('txtAdminReassignSuccess', '✅ Turn reassigned to **[prev_writer]**. **[current_writer]** will go next.', 'en', 1),
('txtAdminReassignNoPreviousWriter', '❌ There is no previous turn to reassign from — this is the first turn in the story.', 'en', 1),

-- Story Thread Activity Log
('txtStoryThreadTurnStart', '✍️ **Turn [turn_number]:** It''s **[writer_name]**''s turn! Deadline: [turn_end_full] ([turn_end_relative]).', 'en', 1),
('txtStoryThreadTurnSkip', '⏭️ **[writer_name]** skipped their turn.', 'en', 1),
('txtStoryThreadTurnTimeout', '⏰ **[writer_name]**''s turn timed out and was automatically skipped.', 'en', 1),
('txtStoryThreadWriterJoin', '👋 **[writer_name]** joined the story.', 'en', 1),
('txtStoryThreadWriterRemove', '🚫 **[writer_name]** was removed from the story by an admin.', 'en', 1),
('txtStoryThreadCreatorTip', '-# ⭐ **Story creator:** Use `/story manage [story_id]` to add a summary, tags, and adjust settings at any time.', 'en', 1),

-- Finalize entry confirmation
('txtFinalizeConfirm', 'Finalize your entry?', 'en', 1),
('txtFinalizeConfirmDesc', 'This will submit everything shown below and advance to the next writer. This cannot be undone.', 'en', 1),
('lblFinalizePreviewEntry', 'Your Entry', 'en', 1),
('btnFinalizeConfirm', 'Yes, Finalize Entry', 'en', 1),
('txtFinalizeImageReview', 'Images in the entry will display with this text:\n*filename : display text*\n[image_list]\n\nTo change the link text, cancel the finalization and edit the image post.', 'en', 1),
('txtNormalModeImageHelp', '📸 **Attaching images:** Upload each image in its own **separate post** in this thread in the order you would like it to appear in the story. The text of that post will become the image''s display label when the story is read. If a post has no text, the filename will be used as the label.', 'en', 1),

-- Skip turn confirmation
('txtSkipConfirmNoContent', '⏭️ **Skip your turn?** This will pass to the next writer without submitting an entry. This cannot be undone.', 'en', 1),
('txtSkipConfirmHasContent', '⚠️ **Skip your turn?** You have posted content in this thread — **it will be discarded** if you skip. This cannot be undone.', 'en', 1),
('btnSkipConfirm', 'Yes, Skip My Turn', 'en', 1),
('btnSkipCancel', 'Cancel', 'en', 1),

-- System Configuration
('cfgLanguageCode', 'en', 'en', 1),
('cfgEntryTimeoutMinutes', '10', 'en', 1),
('errProcessingRequest', 'An error occurred while processing your request.', 'en', 1),

-- Entry edit system
('txtEditEntryNotFound', 'Entry not found or not yet confirmed.', 'en', 1),
('txtEditEntryEmpty', 'Entry content cannot be empty.', 'en', 1),
('txtEditNotAuthorized', 'You don''t have permission to edit this entry.', 'en', 1),
('txtEditSessionExpired', 'Your edit session has expired. Please run /story edit again.', 'en', 1),
('txtEditSuccess', 'Entry updated.', 'en', 1),
('txtEditRestoreSuccess', 'Entry restored.', 'en', 1),
('txtEditHistoryNotFound', 'History version not found.', 'en', 1),
('btnRepostEntry', '📢 Repost to Story Thread', 'en', 1),
('txtRepostSuccess', '✅ Entry reposted to the story thread.', 'en', 1),
('txtRepostThreadNotFound', 'Story thread not found — cannot repost.', 'en', 1),

-- Join UI labels
('lblJoinNotifications', 'Notification Preference:', 'en', 1),
('lblJoinPrivacy', 'Turn Thread Privacy:', 'en', 1),

-- Admin help text
('lblAdminHelpRemove', '/storyadmin remove [story_id] [user]', 'en', 1),
('txtAdminHelpRemove', 'Removes a writer from a story. If it''s their turn, advances to the next writer. If they''re the last writer, the story is closed automatically.', 'en', 1),

-- Request More Time button (on /story timeleft response; also reserved for future reminder notifications)
('btnRequestMoreTime', '⏰ Request More Time', 'en', 1),
('txtRequestMoreTimePost', '**[writer_name]** has requested more time on their turn in **[story_title]**. [admin_role]', 'en', 1),
('txtRequestMoreTimeUsed', '⏰ More time has been requested. An admin will review.', 'en', 1),
('txtRequestMoreTimeAlreadyUsed', 'More time has already been requested for this turn.', 'en', 1),
('txtRequestMoreTimeNotYourTurn', 'This button is only available to the current turn holder.', 'en', 1),
('txtTimeleftNoActiveTurn', 'No active turn found for that story.', 'en', 1),

-- Story export AO3 instructions (shown with the exported HTML file)
('txtExportAO3Instructions', 'If you don''t see a download icon, click the ··· menu on the file and choose **Download**.\n\n**To post to AO3:** Open the file in any text editor and copy everything between the `[body]` and `[/body]` tags. In AO3''s Work Text field, click the **HTML** button to switch to HTML mode, then paste. If your story includes images, you''ll need to host them on an image host and update the links in the file before copying.', 'en', 1),
('btnExportPostPublicly', '📢 Post to Story Thread', 'en', 1),
('txtExportPostedPublicly', '✅ Story file posted to the story thread.', 'en', 1),

-- Turn start notification text (mode-aware, replaces txtDMTurnStart / txtMentionTurnStart for new installs)
-- Tokens: [turn_thread_link] = Discord deep link URL, [story_title] = story title
('txtDMTurnStartQuick', '🎭 **Your turn has started in [story_title]!** [Click here to write your entry.]([turn_thread_link])\n-# Use /mystory help to see your writer commands.', 'en', 1),
('txtMentionTurnStartQuick', '🎭 **Your turn has started in [story_title]!** [Click here to write your entry.]([turn_thread_link])\n-# Use /mystory help to see your writer commands.', 'en', 1),
('txtDMTurnStartNormal', '🎭 **Your turn has started in [story_title]!** You can now write your part of the story in your turn thread: [turn_thread_link]\n-# [Return to the server]([turn_thread_link]) and use `/mystory help` to see the commands available to writers.', 'en', 1),
('txtMentionTurnStartNormal', '🎭 **Your turn has started in [story_title]!** You can now write your part of the story in your turn thread: [turn_thread_link]\n-# Use /mystory help to see the commands available to writers.', 'en', 1),

-- Turn reminder notification text (tokens replaced at send time; [turn_thread_link] requires scheduler implementation)
('txtDMTurnReminderQuick', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). [Click here to write your entry.]([turn_thread_link])', 'en', 1),
('txtMentionTurnReminderQuick', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). [Click here to write your entry.]([turn_thread_link])', 'en', 1),
('txtDMTurnReminderNormal', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). [Return to your turn thread]([turn_thread_link]) to finalize your entry.', 'en', 1),
('txtMentionTurnReminderNormal', '⏰ **Reminder:** Your turn in **[story_title]** is ending soon! Deadline: [turn_end_full] ([turn_end_relative]). Return to your turn thread: [turn_thread_link]', 'en', 1),

-- Story add validation
('txtAddValidationTitleEmpty', 'Story title cannot be empty.', 'en', 1),
('txtAddValidationTitleRequired', 'Please set a story title before creating the story.', 'en', 1),

-- Story list
('txtListFilterPrompt', '🔍 **Filter stories:**', 'en', 1),

-- Story read
('txtReadEntryNotFound', 'Entry not found in session. Please use `/story read` again.', 'en', 1),
('txtReadSessionExpired', 'This reading session has expired. Use `/story read` again.', 'en', 1),

-- Story write
('txtWriteTurnEnded', 'Your turn has already ended — the story has moved on.', 'en', 1),
('txtWriteAlreadySubmitted', 'Your entry has already been submitted.', 'en', 1),

-- Media channel post label (used when forwarding images from turn threads)
('txtMediaPostLabel', '📎 Story #[story_id] — Turn [turn_id]', 'en', 1),

-- /story ping
('txtPingWriters', '📢 [mentions]\n] [message]', 'en', 1),
('txtPingWritersSent', '✅ All active writers have been pinged in the story thread.', 'en', 1),

-- Weekly Roundup
('cfgWeeklyRoundupEnabled', '0', 'en', 1),
('cfgWeeklyRoundupDay', '1', 'en', 1),
('cfgWeeklyRoundupHour', '9', 'en', 1),
('cfgWeeklyRoundupChannelId', '', 'en', 1),
('cfgWeeklyRoundupColor', '57F287', 'en', 1),
('cfgWeeklyRoundupThumbnail', '', 'en', 1),
('txtRoundupDay0', 'Sunday', 'en', 1),
('txtRoundupDay1', 'Monday', 'en', 1),
('txtRoundupDay2', 'Tuesday', 'en', 1),
('txtRoundupDay3', 'Wednesday', 'en', 1),
('txtRoundupDay4', 'Thursday', 'en', 1),
('txtRoundupDay5', 'Friday', 'en', 1),
('txtRoundupDay6', 'Saturday', 'en', 1),
('txtWeeklyRoundupTitle', '📖 Weekly Story Roundup', 'en', 1),
('txtRoundupNoActiveStories', '*No active stories this week.*', 'en', 1),
('txtRoundupStoryLine', '• **[story_title]** (#[story_id])', 'en', 1),
('txtRoundupActivity', 'Stories created: **[created]** · Stories completed: **[completed]**\nTurns submitted: **[submitted]** · Turns missed: **[missed]**\nWords written: **~[word_count]**', 'en', 1),
('txtRoundupOverflow', '*...and [count] more*', 'en', 1),
('lblRoundupActiveStories', '📚 Active Stories', 'en', 1),
('lblRoundupActivity', '📊 This Week''s Activity', 'en', 1),
('lblRoundupWriters', '👥 Active Writers', 'en', 1),

-- Mature/Restricted feed channel config
-- cfgRestrictedFeedChannelId: set to a channel ID that is age-restricted (or the whole server is 18+).
-- cfgRestrictedMediaChannelId: age-restricted equivalent of cfgMediaChannelId.
-- Leave blank to disable the mature feed feature (M/E stories post to the main feed instead).
('cfgRestrictedFeedChannelId', '', 'en', 1),
('cfgRestrictedMediaChannelId', '', 'en', 1),
('txtSetupRestrictedChannelInvalid', '❌ Could not find the restricted feed channel with that ID. Please check and try again.', 'en', 1),
('txtSetupRestrictedMediaInvalid', '❌ Could not find the restricted media channel with that ID. Please check and try again.', 'en', 1),

-- AO3 Metadata labels
('lblRating', 'Rating', 'en', 1),
('lblWarnings', 'Content Warnings', 'en', 1),
('lblFandom', 'Fandom', 'en', 1),
('lblMainPairing', 'Main Pairing', 'en', 1),
('lblOtherRelationships', 'Other Relationships', 'en', 1),
('lblCharacters', 'Characters', 'en', 1),
('lblCategory', 'Category', 'en', 1),
('lblAdditionalTags', 'Additional Tags', 'en', 1),
('btnSetMetadata', 'Story Metadata', 'en', 1),

-- Rating labels
('txtRatingNR', '[NR] Not Rated', 'en', 1),
('txtRatingG', '[G] General', 'en', 1),
('txtRatingT', '[T] Teen', 'en', 1),
('txtRatingM', '[M] Mature', 'en', 1),
('txtRatingE', '[E] Explicit', 'en', 1),

-- Rating change warning (shown in manage panel when rating crosses the M/E barrier)
('txtRatingChangeThreadWarning', '⚠️ **Rating change alert:** Changing the rating across the Mature/Explicit barrier (between G/T/NR and M/E) will start a **new story thread** on the appropriate feed channel when you save. The old thread will be archived and closed. This cannot be undone.', 'en', 1),

-- Read view restricted story error
('txtRestrictedStoryNotHere', '🔞 This story is rated **[rating]** and can only be read in the age-restricted story channel.', 'en', 1),

-- Tag submission system
('btnSubmitTag', '🏷️ Suggest a Tag', 'en', 1),
('txtTagSubmitModalTitle', 'Suggest a Tag', 'en', 1),
('lblTagSubmitText', 'Tag to suggest', 'en', 1),
('txtTagSubmitPlaceholder', 'Enter a single tag (e.g. slow burn, hurt/comfort, AU)', 'en', 1),
('txtTagSubmitSuccess', '✅ Your tag suggestion has been submitted to the story creator for review.', 'en', 1),
('txtTagSubmitNotWriter', '❌ Only active writers in this story can submit tag suggestions.', 'en', 1),
('txtTagSubmitDuplicate', '❌ That tag has already been suggested and is pending review.', 'en', 1),
('txtTagPendingTitle', '🏷️ Pending Tag Suggestions — [story_title]', 'en', 1),
('txtTagNoPending', 'There are no pending tag suggestions for this story.', 'en', 1),
('btnTagApprove', '✅ Approve', 'en', 1),
('btnTagReject', '❌ Reject', 'en', 1),
('txtTagApproved', '✅ Tag **[tag_text]** approved and added to the story.', 'en', 1),
('txtTagRejected', '❌ Tag **[tag_text]** rejected.', 'en', 1),
('txtTagNotCreator', '❌ Only the story creator can review tag suggestions.', 'en', 1),
('txtTagReviewSessionExpired', 'This tag review session has expired. Use /story manage to open tag review again.', 'en', 1),
('btnReviewTags', '🏷️ Review Tags ([count])', 'en', 1),

-- Consistent Save Settings / Selection Staged notice
('btnSaveSettings', '✅ Save Settings', 'en', 1),
('txtSelectionStaged', 'Selection saved — click **Save Settings** on the panel to apply.', 'en', 1),

-- Tag submission — read interface buttons
('btnSubmitTagRead', '🏷️ Submit Tag', 'en', 1),
('btnViewTags', '🏷️ View Tags', 'en', 1),
('btnEditTags', '✏️ Edit Tags', 'en', 1),
('txtTagSubmitModalTitleRead', 'Submit a Tag', 'en', 1),
('txtTagVoteCount', '👍 [up] · 👎 [down]', 'en', 1),
('txtTagVoteNote', '-# Vote in the story thread, or use Approve/Reject below.', 'en', 1),
('txtTagSubmitPosted', '🏷️ **Tag proposed by [submitter_name]:** [tag_text]\nReact 👍 or 👎 to vote.', 'en', 1),
('txtTagSubmitNoThread', '✅ Tag submitted for review. (No story thread found — reaction voting unavailable.)', 'en', 1),
('txtTagViewNone', 'No pending tag submissions for this story.', 'en', 1),

-- MyStory list (merged active+history)
('txtMyListTitle', '📚 Your Stories (Page [page]/[total])', 'en', 1),
('txtMyListNone', 'You have no story history yet. Use `/story join` to get started!', 'en', 1),

-- MyStory manage panel — expanded fields
('btnMyStoryManagePause', '⏸️ Pause Participation', 'en', 1),
('btnMyStoryManageResume', '▶️ Resume Participation', 'en', 1),
('btnMyStoryManagePass', '⏭️ Pass My Turn', 'en', 1),
('btnMyStoryManageLeave', '🚪 Leave Story', 'en', 1),
('lblMyStoryManageStatus', 'Status', 'en', 1),
('txtMyStoryManagePausedStatus', 'Paused', 'en', 1),
('txtMyStoryManageActiveStatus', 'Active', 'en', 1),
('txtMyPassConfirm', '⏭️ **Pass your turn in [story_title]?** This will skip to the next writer without submitting an entry. This cannot be undone.', 'en', 1),
('btnMyPassConfirm', 'Yes, Pass My Turn', 'en', 1),
('txtMyPauseConfirm', '⏸️ **Pause your participation in [story_title]?** You will be removed from the turn rotation. If it is currently your turn, it will be passed automatically. Use Resume to rejoin.', 'en', 1),
('btnMyPauseConfirm', 'Yes, Pause', 'en', 1),
('txtMyResumeSuccess', '▶️ You have rejoined the rotation for **[story_title]**.', 'en', 1),
('txtMyPauseSuccess', '⏸️ You have been paused in **[story_title]**.', 'en', 1),
('txtMyPassSuccess', '✅ Your turn has been passed.', 'en', 1),

-- Admin manage-user panel — expanded fields (notification + privacy editable)
('btnAdminMUSave', '✅ Save Settings', 'en', 1),
('txtAdminMUSaved', '✅ Writer settings saved for **[writer_name]** in **[story_title]**.', 'en', 1),
('lblAdminMUNotif', 'Notifications', 'en', 1),
('lblAdminMUPrivacy', 'Turn Privacy', 'en', 1),
('btnAdminMUToggleNotif', 'Toggle Notifications', 'en', 1),
('btnAdminMUTogglePrivacy', 'Toggle Turn Privacy', 'en', 1),

-- Turn actions panel (inside story manage)
('lblTurnActions', 'Turn Actions', 'en', 1),
('btnTurnSkip', '⏭️ Skip Current Turn', 'en', 1),
('btnTurnExtend', '⏰ Extend Deadline', 'en', 1),
('btnTurnNext', '👆 Designate Next Writer', 'en', 1),
('btnTurnReassign', '↩️ Reassign to Previous', 'en', 1),
('btnTurnDeleteEntry', '🗑️ Delete an Entry', 'en', 1),
('btnTurnRestoreEntry', '♻️ Restore Deleted Entry', 'en', 1),
('txtTurnActionsNoTurn', 'No active turn.', 'en', 1),
('txtTurnSkipConfirm', '⏭️ **Skip [writer_name]''s turn in [story_title]?** This will end their turn immediately and advance to the next writer.', 'en', 1),
('txtTurnExtendModalTitle', 'Extend Deadline', 'en', 1),
('lblTurnExtendHours', 'Hours to add', 'en', 1),
('txtTurnExtendPlaceholder', 'Enter number of hours (e.g. 24)', 'en', 1),
('txtTurnNextModalTitle', 'Designate Next Writer', 'en', 1),
('lblTurnNextUser', 'Discord User ID or mention', 'en', 1),
('txtTurnNextPlaceholder', 'Enter @mention or user ID', 'en', 1),
('txtTurnReassignConfirm', '↩️ **Reassign turn to [prev_writer]?** They will get a new turn immediately, then [current_writer] will go next.', 'en', 1),
('txtTurnDeleteEntryModalTitle', 'Delete Entry by Turn Number', 'en', 1),
('lblTurnDeleteEntryTurn', 'Turn number (as shown in /story read)', 'en', 1),
('txtTurnDeleteEntryPlaceholder', 'Enter turn number', 'en', 1),
('txtTurnRestoreEntryModalTitle', 'Restore Deleted Entry', 'en', 1),
('lblTurnRestoreEntryId', 'Entry ID', 'en', 1),
('txtTurnRestoreEntryPlaceholder', 'Enter entry ID (shown when entry was deleted)', 'en', 1),
('txtTurnNextSelectWrite', 'Select the writer who will receive the next turn:', 'en', 1),

-- Hub server / FAQ forum config (system-level, guild_id = 1)
('cfgHubServerId', '1498673027720679635', 'en', 1),
('cfgHubFaqChannelId', '1499454495044927739', 'en', 1),
('cfgFaqThreadOverview', '', 'en', 1),
('cfgFaqThreadWriterCmds', '', 'en', 1),
('cfgFaqThreadStoryCreation', '', 'en', 1),
('cfgFaqThreadManaging', '', 'en', 1),
('cfgFaqThreadAdminCmds', '', 'en', 1);
